(* ::Package:: *)

(* ::Title::Closed:: *)
(*Setup*)


(* ::Input:: *)
(*Get["C:\\Users\\Miguel\\Github\\libs\\QMB\\Kernel\\init.m"];*)


(* ::Input:: *)
(*SetDirectory[NotebookDirectory[]];*)


(* ::Input:: *)
(*LaunchKernels[10];*)


(* ::Title:: *)
(*Choi State of the Edge-Spin Dynamical Map*)


(* ::Chapter::Closed:: *)
(*Definitions*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 0 -- Kernel and packing utilities                          *)*)
(*(* ================================================================ *)*)
(*$CompileTarget = "WVM";*)
(*Needs["Developer`"];*)
(*ClearAll[PackedC];*)
(*PackedC[x_] := Developer`ToPackedArray[N[x]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 1 -- Pauli operators                                       *)*)
(*(* Packed numerical arrays -- no symbolic overhead.                 *)*)
(*(* ================================================================ *)*)
(*\[Sigma]x  = N[PauliMatrix[1]];*)
(*\[Sigma]y  = N[PauliMatrix[2]];*)
(*\[Sigma]z  = N[PauliMatrix[3]];*)
(*\[Sigma]p  = \[Sigma]x + I*\[Sigma]y;*)
(*\[Sigma]m  = \[Sigma]x - I*\[Sigma]y;*)
(*id2 = N[IdentityMatrix[2]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 2 -- Sparse identity helper                                *)*)
(*(* ================================================================ *)*)
(*SparseId[n_] := SparseArray[Band[{1, 1}] -> 1., {n, n}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 3 -- Hamiltonian embedding functions                       *)*)
(*(*                                                                   *)*)
(*(* Full Hilbert space layout: [Q1, Chain, Q2].                      *)*)
(*(* Dimension: D_total = 2 * 2^L * 2 = 4 * 2^L.                     *)*)
(*(* ================================================================ *)*)
(*Clear[EmbedSpinA, EmbedSpinB, EmbedChain, EmbedChainSite];*)
(*EmbedSpinA[op_, L_]         := KroneckerProduct[op,          SparseId[2^L], SparseId[2]];*)
(*EmbedSpinB[op_, L_]         := KroneckerProduct[SparseId[2], SparseId[2^L], op];*)
(*EmbedChain[Ha_, L_]         := KroneckerProduct[SparseId[2], Ha,            SparseId[2]];*)
(*EmbedChainSite[op_, k_, L_] := KroneckerProduct[SparseId[2^(k-1)], op,     SparseId[2^(L-k)]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 4 -- Boundary coupling constructors                        *)*)
(*(*                                                                   *)*)
(*(* couplingTerms: list of {lambda, opSpin, opChainEdge}.            *)*)
(*(* A-chain couples spin A to the FIRST chain site.                  *)*)
(*(* B-chain couples spin B to the LAST  chain site.                  *)*)
(*(* ================================================================ *)*)
(*Clear[BuildCouplingAChain, BuildCouplingBChain];*)
(*BuildCouplingAChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    term[[2]],*)
(*    KroneckerProduct[term[[3]], SparseId[2^(L-1)]],*)
(*    SparseId[2]*)
(*  ],*)
(*  {term, couplingTerms}*)
(*];*)
(*BuildCouplingBChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    SparseId[2],*)
(*    KroneckerProduct[SparseId[2^(L-1)], term[[2]]],*)
(*    term[[3]]*)
(*  ],*)
(*  {term, couplingTerms}*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 5 -- Full Hamiltonian assembler and diagonalization        *)*)
(*(*                                                                   *)*)
(*(* Returns {eigenvalues, eigenvectors}, eigenvectors as rows.       *)*)
(*(* Eigenvectors are in the [Q1, Chain, Q2] layout.                  *)*)
(*(* ================================================================ *)*)
(*Clear[BuildFullHamiltonian, DiagonalizeH];*)
(*BuildFullHamiltonian[HAlocal_, Ha_, HBlocal_, couplingA_, couplingB_, L_] :=*)
(*  EmbedSpinA[HAlocal, L] +*)
(*  EmbedChain[Ha, L]      +*)
(*  EmbedSpinB[HBlocal, L] +*)
(*  BuildCouplingAChain[couplingA, L] +*)
(*  BuildCouplingBChain[couplingB, L];*)
(*DiagonalizeH[HT_] := Transpose[Sort[Transpose[Eigensystem[Normal[N[HT]]]]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 6 -- Thermal chain state                                   *)*)
(*(*                                                                   *)*)
(*(* Returns the 2^L x 2^L density matrix of the chain at inverse     *)*)
(*(* temperature beta.                                                 *)*)
(*(*   beta = 0        -> maximally mixed (infinite temperature)       *)*)
(*(*   beta = Infinity -> ground-state projector (zero temperature)    *)*)
(*(*   otherwise       -> Gibbs state exp(-beta H) / Z                 *)*)
(*(* ================================================================ *)*)
(*Clear[ThermalChainState];*)
(*ThermalChainState[Ha_, beta_] := Module[*)
(*  {vals, vecs, weights, Z},*)
(*  Which[*)
(*    beta == 0.,*)
(*      N[IdentityMatrix[Length[Ha]]] / Length[Ha],*)
(*    beta === Infinity,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      Outer[Times, vecs[[1]], Conjugate[vecs[[1]]]],*)
(*    True,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      weights = Exp[-beta * (vals - Min[vals])];*)
(*      Z = Total[weights];*)
(*      ConjugateTranspose[vecs] . DiagonalMatrix[N[weights / Z]] . vecs*)
(*  ]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 7 -- Beta label helpers                                    *)*)
(*(* ================================================================ *)*)
(*BetaStr[beta_] := Which[*)
(*  beta == 0.,        "b0p0",*)
(*  beta == 0.5,       "b0p5",*)
(*  beta == 1.,        "b1p0",*)
(*  beta == 2.,        "b2p0",*)
(*  beta === Infinity, "bInf",*)
(*  True, "b" <> StringReplace[*)
(*    ToString[NumberForm[N[beta], {3,1}]], "." -> "p"]*)
(*];*)
(*BetaLabel[beta_] := Which[*)
(*  beta == 0.,        "\[Beta]=0  (T\[Rule]\[Infinity])",*)
(*  beta === Infinity, "\[Beta]=\[Infinity]  (T=0)",*)
(*  True, "\[Beta]=" <> ToString[NumberForm[N[beta], {3,1}]]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 8 -- Eigenvector column permutation: [Q1,Chain,Q2] -> [Q1,Q2,Chain] *)*)
(*(*                                                                   *)*)
(*(* The full Hamiltonian is built in the [Q1, Chain, Q2] tensor      *)*)
(*(* product order with dimensions [2, 2^L, 2].  The Choi channel     *)*)
(*(* construction requires the unitary to act on S x E where          *)*)
(*(*   S = Q1 x Q2  (the two edge spins, dS = 4)                      *)*)
(*(*   E = Chain    (the environment,   dE = 2^L)                      *)*)
(*(* The required column-index order is therefore [Q1, Q2, Chain].    *)*)
(*(*                                                                   *)*)
(*(* For a D_total-dimensional vector in [Q1, Chain, Q2]:             *)*)
(*(*   reshape to {2, 2^L, 2} -> Transpose to {2, 2, 2^L} -> flatten  *)*)
(*(* Applied row-by-row to the eigenvector matrix (rows = vectors).   *)*)
(*(* ================================================================ *)*)
(*Clear[PermuteEvecsToSE];*)
(*PermuteEvecsToSE[Evec_, L_] := Module[*)
(*  {dC = 2^L},*)
(*  PackedC@Table[*)
(*    Flatten[Transpose[ArrayReshape[Evec[[alpha]], {2, dC, 2}], {1, 3, 2}]],*)
(*    {alpha, 1, Length[Evec]}*)
(*  ]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 9 -- Spectral unitary                                      *)*)
(*(*                                                                   *)*)
(*(* Returns Function[t, U(t)] where                                  *)(*
(*   U(t) = P . Diag(e^{-i lambda t}) . P^dagger                     *)*)
(*(*                                                                   *)*)
(*(* allvecs: D x D matrix, rows are eigenvectors in S x E order.     *)*)
(*(* allvals: length-D eigenvalue vector.                              *)*)
(*(* ================================================================ *)*)
(*ClearAll[SpectralUnitary];*)
(*SpectralUnitary[allvecs_, allvals_] :=*)
(*  Module[{Pmat  = PackedC@Transpose[allvecs],*)
(*          Pinv  = PackedC@Conjugate[allvecs]},*)
(*    Function[{t},*)
(*      With[{ph = PackedC@Exp[-I allvals t]},*)
(*        PackedC@(Transpose[Transpose[Pmat]*ph] . Pinv)]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 10 -- Maximally entangled state projector |Phi+><Phi+|     *)*)
(*(*                                                                   *)*)
(*(* |Phi+> = dS^{-1/2} Sum_i |i>_R|i>_S  in the reference-system    *)*)
(*(* bipartition.  Precomputed once; independent of t and rhoE.       *)*)
(*(* ================================================================ *)*)
(*ClearAll[MakePhiProjector];*)
(*MakePhiProjector[dS_Integer?Positive] :=*)
(*  Module[{phi = PackedC@(Flatten[IdentityMatrix[dS]]/Sqrt[dS])},*)
(*    PackedC@Dyad[phi]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 11 -- Choi channel builder                                 *)*)
(*(*                                                                   *)*)
(*(* Constructs the time-dependent Choi matrix of the dynamical map   *)*)
(*(* E_t acting on S = Q1 x Q2, via:                                  *)*)
(*(*                                                                   *)*)
(*(*   choiMat(t) = Tr_E[(I_R x U(t))(|Phi+><Phi+| x rhoE)           *)*)
(*(*                     (I_R x U(t))^dagger]                          *)*)
(*(*                                                                   *)*)
(*(* U(t) acts on S x E; I_R is the identity on the reference copy R. *)*)
(*(* The trace is over E = Chain (subsystem 3 of {dS, dS, dE}).       *)*)
(*(*                                                                   *)*)
(*(* Returns a Function[t, choiMat(t)]: a closure holding rhoE,       *)*)
(*(* projPhi, and the spectral unitary.                                *)*)
(*(*                                                                   *)*)
(*(* "rhoE" -> dE x dE matrix: environment initial density matrix.    *)*)
(*(* ================================================================ *)*)
(*ClearAll[ChoiChannelF];*)
(*Options[ChoiChannelF] = {"rhoE" -> None};*)
(**)
(*ChoiChannelF[dS_Integer?Positive, dE_Integer?Positive,*)
(*             unitaryF_Function, opts:OptionsPattern[]] :=*)
(*  Module[{rhoEval = OptionValue["rhoE"],*)
(*          projPhi, idRef},*)
(*    If[rhoEval === None,*)
(*      Message[ChoiChannelF::noenv]; Return[$Failed]];*)
(*    rhoEval = PackedC@rhoEval;*)
(*    projPhi = MakePhiProjector[dS];*)
(*    idRef   = IdentityMatrix[dS, SparseArray];*)
(*    Function[{t},*)
(*      Module[{Ut = unitaryF[t], URt, OmegaMat, fullMat},*)
(*        URt      = KroneckerProduct[idRef, Ut];*)
(*        OmegaMat = KroneckerProduct[projPhi, rhoEval];*)
(*        fullMat  = URt . OmegaMat . ConjugateTranspose[URt];*)
(*        PackedC@Chop@MatrixPartialTrace[fullMat, 3, {dS, dS, dE}]]]];*)
(**)
(*ChoiChannelF::noenv = "Provide \"rhoE\" -> (dE x dE matrix).";*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 12 -- Choi state observables                               *)*)
(*(*                                                                   *)*)
(*(* All scalar quantities derived from the dS^2 x dS^2 Choi matrix. *)*)
(*(* Argument name: choiMat (never D, reserved as derivative).        *)*)
(*(*                                                                   *)*)
(*(* ChoiPurity   : Tr[choiMat^2].  Bounds: [1/dS^2, 1].             *)*)
(*(* ChoiVNEntropy: -Tr[choiMat log choiMat]. Bounds: [0, log(dS^2)]. *)*)
(*(* ChoiEVals    : sorted descending eigenvalues of choiMat.          *)*)
(*(* ChoiAllObs   : single aggregator returning an Association.        *)*)
(*(* ================================================================ *)*)
(*ClearAll[ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs];*)
(**)
(*ChoiPurity[choiMat_] := Chop@Re@Tr[choiMat . choiMat];*)
(**)
(*ChoiVNEntropy[choiMat_] :=*)
(*  Module[{ev = Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &]},*)
(*    ev = ev / Total[ev];*)
(*    Chop@(-ev . Log[ev])];*)
(**)
(*ChoiEVals[choiMat_] :=*)
(*  Sort[Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &], Greater];*)
(**)
(*ChoiAllObs[choiMat_] :=*)
(*  Module[{ev = Sort[Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &], Greater],*)
(*          evNorm},*)
(*    evNorm = ev / Total[ev];*)
(*    <|"Purity"      -> Chop@Re@Tr[choiMat . choiMat],*)
(*      "VNEntropy"   -> Chop@(-evNorm . Log[evNorm]),*)
(*      "Eigenvalues" -> ev,*)
(*      "Rank"        -> Length[ev]|>];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 13 -- Time-series driver                                   *)*)
(*(*                                                                   *)*)
(*(* Evaluates choiFn at each t in tlist and computes Choi observables.*)*)
(*(* Returns a List of Associations keyed by "Time".                  *)*)
(*(*                                                                   *)*)
(*(* "Observables" option:                                             *)*)
(*(*   "Purity"  -- Tr[choiMat^2] only                                *)*)
(*(*   "Entropy" -- Purity + von Neumann entropy                       *)*)
(*(*   "All"     -- all of the above plus eigenvalue list and rank     *)*)
(*(*                                                                   *)*)
(*(* "Parallel" option: True (default) uses ParallelMap with           *)*)
(*(* DistributedContexts -> None (workers already loaded upstream).   *)*)
(*(* ================================================================ *)*)
(*ClearAll[ChoiSeries];*)
(*Options[ChoiSeries] = {"Observables" -> "All", "Parallel" -> True};*)
(**)
(*ChoiSeries[choiFn_Function, tlist_List, OptionsPattern[]] :=*)
(*  Module[{obsOpt = OptionValue["Observables"],*)
(*          parOpt = TrueQ[OptionValue["Parallel"]],*)
(*          stepFn},*)
(*    stepFn = Function[{t},*)
(*      Module[{choiMat = choiFn[t], obsResult},*)
(*        obsResult = Switch[obsOpt,*)
(*          "Purity",*)
(*            <|"Purity" -> ChoiPurity[choiMat]|>,*)
(*          "Entropy",*)
(*            Module[{ev = Sort[Select[Re[Eigenvalues[N[choiMat]]],*)
(*                                    # > 1.*^-14 &], Greater]},*)
(*              ev = ev / Total[ev];*)
(*              <|"Purity"    -> Chop@Re@Tr[choiMat . choiMat],*)
(*                "VNEntropy" -> Chop@(-ev . Log[ev])|>],*)
(*          _, (* "All" *)*)
(*            ChoiAllObs[choiMat]];*)
(*        Join[<|"Time" -> t|>, obsResult]]];*)
(*    If[parOpt,*)
(*      ParallelMap[stepFn, tlist,*)
(*        Method -> "CoarsestGrained",*)
(*        DistributedContexts -> None],*)
(*      Map[stepFn, tlist]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 14 -- Result extraction utilities                          *)*)
(*(*                                                                   *)*)
(*(* ExtractTS   : {time, value} pairs for a scalar key.              *)*)
(*(* ExtractEVals: pads eigenvalue lists to uniform length nKeep,     *)*)
(*(*   returns nKeep series of {{t, lambda_k}...} for plotting.       *)*)
(*(*   Missing eigenvalues (numerical zero) filled with 0.            *)*)
(*(* ================================================================ *)*)
(*ClearAll[ExtractTS, ExtractEVals];*)
(**)
(*ExtractTS[res_List, key_String] :=*)
(*  {#["Time"], #[key]} & /@ res;*)
(**)
(*ExtractEVals[res_List, nKeep_Integer] :=*)
(*  Table[*)
(*    {#["Time"],*)
(*     If[Length[#["Eigenvalues"]] >= k, #["Eigenvalues"][[k]], 0.]} & /@ res,*)
(*    {k, 1, nKeep}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 15 -- MakePlotsChoi                                        *)*)
(*(*                                                                   *)*)
(*(* Generates and exports all PNG files for one (L, k, beta) run.    *)*)
(*(* Filenames: Observable_D07_b1p0.png inside baseDir/L=5/Choi/      *)*)
(*(*                                                                   *)*)
(*(* Plots exported:                                                   *)*)
(*(*   ChoiPurity       -- Tr[choiMat(t)^2]  with 1/dS^2 reference    *)*)
(*(*   ChoiVNEntropy    -- -Tr[choiMat log choiMat] with log(dS^2) ref *)*)
(*(*   ChoiEigenvalues  -- top 4 eigenvalues vs time                   *)*)
(*(*   ChoiRank         -- rank(choiMat(t)) vs time                    *)*)
(*(*   ChoiAllObs       -- Purity + VNEntropy on one panel             *)*)
(*(*   data .mx         -- full results list                           *)*)
(*(* ================================================================ *)*)
(*MakePlotsChoi[results_, L_, k_, beta_, dS_, dE_, dir_] := Module[*)
(*  {delta, label, ext, get, commonOpts, purityTS, entropyTS,*)
(*   rankTS, evSeries, nPlot, evColors, evStyles, evLabels},*)
(**)
(*  delta = N[k/10];*)
(*  label = "XXZ edge-spin Choi,  L=" <> ToString[L] <>*)
(*          ",  \[CapitalDelta]=" <> ToString[NumberForm[delta, {3,1}]] <>*)
(*          ",  " <> BetaLabel[beta] <>*)
(*          ",  h1=" <> ToString[h1sweep] <>*)
(*          ",  h2=" <> ToString[h2sweep] <>*)
(*          ",  dS=" <> ToString[dS];*)
(*  ext = "_D" <> StringPadLeft[ToString[k], 2, "0"] <>*)
(*        "_"  <> BetaStr[beta] <> ".png";*)
(**)
(*  get[key_] := {#["Time"], #[key]} & /@ results;*)
(**)
(*  commonOpts = Sequence[*)
(*    Frame      -> True,*)
(*    LabelStyle -> Directive[Black, 16],*)
(*    PlotLabel  -> Style[label, Black, 13],*)
(*    ImageSize  -> 700,*)
(*    PlotRange  -> All*)
(*  ];*)
(**)
(*  (* Purity with depolarizing lower bound *)*)
(*  purityTS = get["Purity"];*)
(*  Export[FileNameJoin[{dir, "ChoiPurity" <> ext}],*)
(*    Show[*)
(*      ListLinePlot[purityTS,*)
(*        FrameLabel -> {"Time (t)", "Tr[\[ScriptCapitalE](t)\[CenterDot]\[ScriptCapitalE](t)]"},*)
(*        PlotStyle  -> {Thick, Black}, commonOpts],*)
(*      Plot[1/dS^2, {t, 0, tMax},*)
(*        PlotStyle -> Directive[Red, Dashed, Thick]]]];*)
(**)
(*  (* Von Neumann entropy with depolarizing upper bound *)*)
(*  entropyTS = get["VNEntropy"];*)
(*  Export[FileNameJoin[{dir, "ChoiVNEntropy" <> ext}],*)
(*    Show[*)
(*      ListLinePlot[entropyTS,*)
(*        FrameLabel -> {"Time (t)", "S(\[ScriptCapitalE](t))"},*)
(*        PlotStyle  -> {Thick, Blue}, commonOpts],*)
(*      Plot[Log[dS^2], {t, 0, tMax},*)
(*        PlotStyle -> Directive[Red, Dashed, Thick]]]];*)
(**)
(*  (* Rank *)*)
(*  rankTS = get["Rank"];*)
(*  Export[FileNameJoin[{dir, "ChoiRank" <> ext}],*)
(*    ListLinePlot[rankTS,*)
(*      FrameLabel -> {"Time (t)", "Rank[\[ScriptCapitalE](t)]"},*)
(*      PlotStyle  -> {Thick, Darker[Green]}, commonOpts]];*)
(**)
(*  (* Top 4 eigenvalues *)*)
(*  nPlot    = 4;*)
(*  evSeries = ExtractEVals[results, nPlot];*)
(*  evColors = {Black, Red, Blue, Darker[Green]};*)
(*  evStyles = Directive[#, Thick] & /@ evColors;*)
(*  evLabels = Table[Style["\[Lambda]" <> ToString[k2], 15], {k2, 1, nPlot}];*)
(*  Export[FileNameJoin[{dir, "ChoiEigenvalues" <> ext}],*)
(*    ListLinePlot[evSeries,*)
(*      FrameLabel  -> {"Time (t)", "\[Lambda]k(t)"},*)
(*      PlotStyle   -> evStyles,*)
(*      PlotLegends -> Placed[LineLegend[evColors, evLabels,*)
(*                       LegendLayout -> "Column"], Right],*)
(*      commonOpts]];*)
(**)
(*  (* Combined panel: Purity + VNEntropy *)*)
(*  Export[FileNameJoin[{dir, "ChoiAllObs" <> ext}],*)
(*    ListLinePlot[*)
(*      {purityTS, entropyTS},*)
(*      FrameLabel  -> {"Time (t)", "Choi Observables"},*)
(*      PlotStyle   -> {Directive[Thick, Black], Directive[Thick, Blue]},*)
(*      PlotLegends -> Placed[LineLegend[*)
(*        {Black, Blue},*)
(*        {"Purity Tr[\[ScriptCapitalE]^2]", "Entropy S(\[ScriptCapitalE])"},*)
(*        LegendFunction -> Framed], Right],*)
(*      commonOpts]];*)
(**)
(*  (* Binary .mx for fast Mathematica reloading *)*)
(*  Export[FileNameJoin[{dir,*)
(*    "choi_data_D" <> StringPadLeft[ToString[k], 2, "0"] <>*)
(*    "_" <> BetaStr[beta] <> ".mx"}],*)
(*    results];*)
(*];*)


(* ::Input:: *)
(*(* Distribute all reusable definitions to parallel kernels.         *)*)
(*(* Called once after the Definitions chapter.                       *)*)
(*DistributeDefinitions[*)
(*  PackedC, MakePhiProjector, SpectralUnitary, ChoiChannelF,*)
(*  ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs,*)
(*  ExtractTS, ExtractEVals,*)
(*  MatrixPartialTrace, Dyad*)
(*];*)


(* ::Chapter::Closed:: *)
(*Fixed Parameters*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODEL SPECIFICATION                                              *)*)
(*(* This block is the only section that changes between runs.        *)*)
(*(* Hamiltonian parameters and coupling form are identical to        *)*)
(*(* spin_channels_clean.m.                                           *)*)
(*(* ================================================================ *)*)
(*{\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = {1.1, 0.9, 1., 1.};*)
(*{h1sweep, h2sweep}  = {0.99, 1.01};*)
(*tMax  = 100.;*)
(*dt    = 0.1;*)
(*tlist = Range[0., tMax, dt];*)
(**)
(*HAlocal   = \[CapitalDelta]a * \[Sigma]z;*)
(*HBlocal   = \[CapitalDelta]b * \[Sigma]z;*)
(*couplingA = {{\[Lambda]a, \[Sigma]p, \[Sigma]m}, {\[Lambda]a, \[Sigma]m, \[Sigma]p}};*)
(*couplingB = {{\[Lambda]b, \[Sigma]p, \[Sigma]m}, {\[Lambda]b, \[Sigma]m, \[Sigma]p}};*)
(**)
(*(* System and environment dimensions for the Choi construction.     *)*)
(*(* S = Q1 x Q2 (both edge spins), dS = 4.                          *)*)
(*(* E = Chain, dE = 2^L (set inside the L loop).                    *)*)
(*dS = 4;*)
(**)
(*(* Base output directory *)*)
(*baseDir = NotebookDirectory[];*)


(* ::Input:: *)
(*betaList   = {0., 0.01, 0.5, 1., 5., Infinity};*)


(* ::Input:: *)
(*LList      = Range[6, 8];*)
(*kDeltaList = Range[4, 16, 2];*)


(* ::Chapter:: *)
(*Sweep*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* Outer loop: L                                                     *)*)
(*(* Inner loop: delta (via integer key k, delta = k/10)              *)*)
(*(* Innermost loop: beta                                              *)*)
(*(*                                                                   *)*)
(*(* Per (L, k) pair:                                                  *)*)
(*(*   1. Build the full Hamiltonian HT in [Q1, Chain, Q2] layout.    *)*)
(*(*   2. Diagonalize -> {Eval, Evec}.                                 *)*)
(*(*   3. Permute Evec columns: [Q1,Chain,Q2] -> [Q1,Q2,Chain] = SxE. *)*)
(*(*   4. Build SpectralUnitary from permuted Evec and Eval.           *)*)
(*(*                                                                   *)*)
(*(* Per beta (given the above precomputed objects):                   *)*)
(*(*   5. Build ThermalChainState -> rhoChain (dE x dE).              *)*)
(*(*   6. Build ChoiChannelF with rhoE = rhoChain.                    *)*)
(*(*   7. Sanity check choiFn at t=0: must give Tr[choiMat^2] = 1.    *)*)
(*(*   8. Distribute choiFn to parallel kernels.                       *)*)
(*(*   9. Run ChoiSeries over tlist.                                   *)*)
(*(*  10. Export plots and .mx via MakePlotsChoi.                      *)*)
(*(* ================================================================ *)*)
(*Do[*)
(*  dirL    = FileNameJoin[{baseDir, "L=" <> ToString[L]}];*)
(*  dirChoi = FileNameJoin[{dirL, "Choi"}];*)
(*  If[!DirectoryQ[dirL],    CreateDirectory[dirL]];*)
(*  If[!DirectoryQ[dirChoi], CreateDirectory[dirChoi]];*)
(**)
(*  Do[*)
(*    delta = N[k/10];*)
(*    Print["L = ", L, "   \[CapitalDelta] = ", NumberForm[delta, {3,1}], "   ..."];*)
(**)
(*    (* Build and diagonalize once per (L, delta) *)*)
(*    Ha           = OpenXXZHamiltonian[L, delta, h1sweep, h2sweep];*)
(*    HT           = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal,*)
(*                         couplingA, couplingB, L]];*)
(*    {Eval, Evec} = DiagonalizeH[HT];*)
(*    Clear[HT];*)
(**)
(*    (* dE for this L *)*)
(*    dE = 2^L;*)
(**)
(*    (* Permute eigenvectors: [Q1,Chain,Q2] -> [Q1,Q2,Chain] = S x E *)*)
(*    EvecSE = PermuteEvecsToSE[Evec, L];*)
(*    Clear[Evec];*)
(**)
(*    (* SpectralUnitary is beta-independent: build once per (L, delta) *)*)
(*    unitaryFn = SpectralUnitary[EvecSE, Eval];*)
(*    Clear[EvecSE];*)
(**)
(*    (* Beta loop *)*)
(*    Do[*)
(*      beta = betaList[[ib]];*)
(*      Print["    \[Beta] = ", BetaLabel[beta], "   ..."];*)
(*      t0 = AbsoluteTime[];*)
(**)
(*      (* Environment initial state: thermal chain state at inverse temperature beta *)*)
(*      rhoChain = ThermalChainState[Ha, beta];*)
(**)
(*      (* Build Choi channel closure *)*)
(*      choiFn = ChoiChannelF[dS, dE, unitaryFn, "rhoE" -> rhoChain];*)
(*      Clear[rhoChain];*)
(**)
(*      (* Sanity check: U(0) = identity => E_0 = identity channel => *)*)
(*      (*   choiMat(0) = |Phi+><Phi+|, purity = 1 *)*)
(*      choi0 = choiFn[0.];*)
(*      Print["      t=0 check: Tr[choiMat^2] = ", ChoiPurity[choi0],*)
(*            "  (expected 1)   Tr[choiMat] = ", N@Re@Tr[choi0],*)
(*            "  (expected 1)"];*)
(*      Clear[choi0];*)
(**)
(*      (* Distribute to parallel kernels *)*)
(*      DistributeDefinitions[*)
(*        choiFn,*)
(*        PackedC, MakePhiProjector, ChoiChannelF,*)
(*        ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs,*)
(*        MatrixPartialTrace, Dyad*)
(*      ];*)
(**)
(*      (* Time evolution: compute Choi observables at every t in tlist *)*)
(*      AbsoluteTiming[*)
(*        choiResults = ChoiSeries[choiFn, tlist,*)
(*          "Observables" -> "All",*)
(*          "Parallel"    -> True];*)
(*      ];*)
(**)
(*      Clear[choiFn];*)
(**)
(*      (* Export plots and binary data *)*)
(*      MakePlotsChoi[choiResults, L, k, beta, dS, dE, dirChoi];*)
(*      Clear[choiResults];*)
(**)
(*      Print["      done in ", Round[AbsoluteTime[] - t0, 0.1], " s"];*)
(**)
(*      , {ib, Length[betaList]}*)
(*    ];*)
(**)
(*    (* Cleared after full beta loop for this (L, delta) *)*)
(*    Clear[Ha, unitaryFn, Eval];*)
(**)
(*    , {k, kDeltaList}*)
(*  ];*)
(**)
(*  , {L, LList}*)
(*];*)
(**)
(*Print["Choi sweep complete."];*)
