(* ::Package:: *)

(* ::Title::Closed:: *)
(*Setup*)


(* ::Input:: *)
(*Get["C:\\Users\\Miguel\\Github\\libs\\QMB\\Kernel\\init.m"];*)


(* ::Input:: *)
(*SetDirectory[NotebookDirectory[]];*)


(* ::Input:: *)
(*LaunchKernels[10];*)


(* ::Input:: *)
(*Names["QMB`*"]*)


(* ::Title:: *)
(*Choi State Thermal Sweep -- Transfer-Tensor Method*)


(* ::Text:: *)
(*Computes chi(t) of the edge-spin dynamical map for a list of chain lengths  *)
(*LList and inverse temperatures betaList, with delta fixed. Uses the validated *)
(*transfer-tensor construction (Method 2 of choi_methods_comparison.m) throughout -- *)
(*the brute-force branch (Method 1 / ChoiChannelF) is not present in this file.    *)
(*                                                                                  *)
(*Key precomputation separation:                                                     *)
(*  Per (L, delta): Ha, {Eval, Evec}, Tmat, Ucols, dEflat -- built once.            *)
(*  Per (L, delta, beta): rhoChain, KmatFast, choiFnFast -- built per beta.          *)
(*                                                                                  *)
(*Output per (L, beta) run:                                                          *)
(*  ChoiObservables_D<kk>_<betastr>.png  -- Purity and VNEntropy                    *)
(*  ChoiEigenvalues5_D<kk>_<betastr>.png -- first 5 eigenvalues of chi(t)           *)
(*  choi_data_D<kk>_<betastr>.mx         -- full ChoiSeries result list             *)
(*All files written to baseDir/L=<LL>/Choi/.                                        *)


(* ::Chapter::Closed:: *)
(*Definitions*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 0 -- Kernel and packing                                    *)*)
(*(* ================================================================ *)*)
(*$CompileTarget = "C";*)
(*$HistoryLength = 0;*)
(*Needs["Developer`"];*)
(*ClearAll[PackedC];*)
(*PackedC[x_] := Developer`ToPackedArray[N[x]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 1 -- Pauli operators                                       *)*)
(*(* ================================================================ *)*)
(*\[Sigma]x  = N[PauliMatrix[1]];*)
(*\[Sigma]y  = N[PauliMatrix[2]];*)
(*\[Sigma]z  = N[PauliMatrix[3]];*)
(*\[Sigma]p  = \[Sigma]x + I*\[Sigma]y;*)
(*\[Sigma]m  = \[Sigma]x - I*\[Sigma]y;*)
(*id2 = N[IdentityMatrix[2]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 2 -- Sparse identity helper                                *)*)
(*(* ================================================================ *)*)
(*SparseId[n_] := SparseArray[Band[{1, 1}] -> 1., {n, n}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 3 -- Hamiltonian embedding, [Q1, Chain, Q2] layout         *)*)
(*(* ================================================================ *)*)
(*Clear[EmbedSpinA, EmbedSpinB, EmbedChain, EmbedChainSite];*)
(*EmbedSpinA[op_, L_]         := KroneckerProduct[op,          SparseId[2^L], SparseId[2]];*)
(*EmbedSpinB[op_, L_]         := KroneckerProduct[SparseId[2], SparseId[2^L], op];*)
(*EmbedChain[Ha_, L_]         := KroneckerProduct[SparseId[2], Ha,            SparseId[2]];*)
(*EmbedChainSite[op_, k_, L_] := KroneckerProduct[SparseId[2^(k-1)], op,     SparseId[2^(L-k)]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 4 -- Boundary coupling constructors                        *)*)
(*(* ================================================================ *)*)
(*Clear[BuildCouplingAChain, BuildCouplingBChain];*)
(*BuildCouplingAChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    term[[2]],*)
(*    KroneckerProduct[term[[3]], SparseId[2^(L-1)]],*)
(*    SparseId[2]],*)
(*  {term, couplingTerms}];*)
(*BuildCouplingBChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    SparseId[2],*)
(*    KroneckerProduct[SparseId[2^(L-1)], term[[2]]],*)
(*    term[[3]]],*)
(*  {term, couplingTerms}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 5 -- Full Hamiltonian assembler and diagonalization        *)*)
(*(* Returns {eigenvalues, eigenvectors}, eigenvectors as rows.       *)*)
(*(* ================================================================ *)*)
(*Clear[BuildFullHamiltonian, DiagonalizeH];*)
(*BuildFullHamiltonian[HAlocal_, Ha_, HBlocal_, couplingA_, couplingB_, L_] :=*)
(*  EmbedSpinA[HAlocal, L] +*)
(*  EmbedChain[Ha, L]      +*)
(*  EmbedSpinB[HBlocal, L] +*)
(*  BuildCouplingAChain[couplingA, L] +*)
(*  BuildCouplingBChain[couplingB, L];*)
(*DiagonalizeH[HT_] := Transpose[Sort[Transpose[Eigensystem[Normal[N[HT]]]]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 6 -- Thermal chain state                                   *)*)
(*(*   beta = 0.       -> maximally mixed                              *)*)
(*(*   beta = Infinity -> ground-state projector                       *)*)
(*(*   otherwise       -> Gibbs state exp(-beta H) / Z                 *)*)
(*(* ================================================================ *)*)
(*Clear[ThermalChainState];*)
(*ThermalChainState[Ha_, beta_] := Module[*)
(*  {vals, vecs, weights, Z},*)
(*  Which[*)
(*    beta == 0.,*)
(*      N[IdentityMatrix[Length[Ha]]] / Length[Ha],*)
(*    beta === Infinity,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      Outer[Times, vecs[[1]], Conjugate[vecs[[1]]]],*)
(*    True,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      weights = Exp[-beta * (vals - Min[vals])];*)
(*      Z = Total[weights];*)
(*      ConjugateTranspose[vecs] . DiagonalMatrix[N[weights / Z]] . vecs]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 7 -- Beta label helpers (file names and plot labels)       *)*)
(*(* ================================================================ *)*)
(*BetaStr[beta_] := Which[*)
(*  beta == 0.,        "b0p0",*)
(*  beta == 0.5,       "b0p5",*)
(*  beta == 1.,        "b1p0",*)
(*  beta == 2.,        "b2p0",*)
(*  beta === Infinity, "bInf",*)
(*  True, "b" <> StringReplace[*)
(*    ToString[NumberForm[N[beta], {3,1}]], "." -> "p"]];*)
(*BetaLabel[beta_] := Which[*)
(*  beta == 0.,        "\[Beta]=0  (T\[Rule]\[Infinity])",*)
(*  beta === Infinity, "\[Beta]=\[Infinity]  (T=0)",*)
(*  True, "\[Beta]=" <> ToString[NumberForm[N[beta], {3,1}]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 8 -- Choi state observables                               *)*)
(*(*   ChoiPurity    : Tr[chi^2].  Bounds: [1/dS^2, 1].               *)*)
(*(*   ChoiVNEntropy : -Tr[chi log chi]. Bounds: [0, log(dS^2)].       *)*)
(*(*   ChoiEVals     : eigenvalues, sorted descending, nonzero only.   *)*)
(*(*   ChoiAllObs    : all of the above in one Association.            *)*)
(*(* ================================================================ *)*)
(*ClearAll[ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs];*)
(**)
(*ChoiPurity[choiMat_] := Chop@Re@Tr[choiMat . choiMat];*)
(**)
(*ChoiVNEntropy[choiMat_] :=*)
(*  Module[{ev = Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &]},*)
(*    ev = ev / Total[ev];*)
(*    Chop@(-ev . Log[ev])];*)
(**)
(*ChoiEVals[choiMat_] :=*)
(*  Sort[Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &], Greater];*)
(**)
(*ChoiAllObs[choiMat_] :=*)
(*  Module[{ev = Sort[Select[Re[Eigenvalues[N[choiMat]]], # > 1.*^-14 &], Greater],*)
(*          evNorm},*)
(*    evNorm = ev / Total[ev];*)
(*    <|"Purity"      -> Chop@Re@Tr[choiMat . choiMat],*)
(*      "VNEntropy"   -> Chop@(-evNorm . Log[evNorm]),*)
(*      "Eigenvalues" -> ev,*)
(*      "Rank"        -> Length[ev]|>];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 9 -- Time-series driver                                    *)*)
(*(*                                                                   *)*)
(*(* Evaluates choiFn at each t in tlist; computes Choi observables.  *)*)
(*(* Returns a List of Associations keyed by "Time".                  *)*)
(*(*                                                                   *)*)
(*(* "Parallel" -> True: uses ParallelMap with DistributedContexts ->  *)*)
(*(* None (workers pre-loaded before the loop).                        *)*)
(*(* ================================================================ *)*)
(*ClearAll[ChoiSeries];*)
(*Options[ChoiSeries] = {"Observables" -> "All", "Parallel" -> True};*)
(**)
(*ChoiSeries[choiFn_Function, tlist_List, OptionsPattern[]] :=*)
(*  Module[{obsOpt = OptionValue["Observables"],*)
(*          parOpt = TrueQ[OptionValue["Parallel"]],*)
(*          stepFn},*)
(*    stepFn = Function[{t},*)
(*      Module[{choiMat = choiFn[t], obsResult},*)
(*        obsResult = Switch[obsOpt,*)
(*          "Purity",*)
(*            <|"Purity" -> ChoiPurity[choiMat]|>,*)
(*          "Entropy",*)
(*            Module[{ev = Sort[Select[Re[Eigenvalues[N[choiMat]]],*)
(*                                    # > 1.*^-14 &], Greater]},*)
(*              ev = ev / Total[ev];*)
(*              <|"Purity"    -> Chop@Re@Tr[choiMat . choiMat],*)
(*                "VNEntropy" -> Chop@(-ev . Log[ev])|>],*)
(*          _,*)
(*            ChoiAllObs[choiMat]];*)
(*        Join[<|"Time" -> t|>, obsResult]]];*)
(*    If[parOpt,*)
(*      ParallelMap[stepFn, tlist,*)
(*        Method -> "CoarsestGrained",*)
(*        DistributedContexts -> None],*)
(*      Map[stepFn, tlist]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 10 -- Result extraction utilities                          *)*)
(*(*   ExtractTS  : {time, value} pairs for a scalar key.             *)*)
(*(*   ExtractEVals: nKeep series of {{t, lambda_k}...}; missing      *)*)
(*(*                 eigenvalues filled with 0 (numerical zero rank).  *)*)
(*(* ================================================================ *)*)
(*ClearAll[ExtractTS, ExtractEVals];*)
(**)
(*ExtractTS[res_List, key_String] :=*)
(*  {#["Time"], #[key]} & /@ res;*)
(**)
(*ExtractEVals[res_List, nKeep_Integer] :=*)
(*  Table[*)
(*    {#["Time"],*)
(*     If[Length[#["Eigenvalues"]] >= kk, #["Eigenvalues"][[kk]], 0.]} & /@ res,*)
(*    {kk, 1, nKeep}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 11 -- Transfer tensor builder                              *)*)
(*(*                                                                   *)*)
(*(* T[[q1+1,q2+1,q1p+1,q2p+1]]: D_total x D_total matrix.           *)*)
(*(* Depends only on Evec and L. Built ONCE per (L, delta).            *)*)
(*(* Reused across all beta values for that (L, delta).               *)*)
(*(* ================================================================ *)*)
(*Clear[BuildTransferTensors];*)
(*BuildTransferTensors[U_, L_] := Module[*)
(*  {dC, idxFull, getCols},*)
(*  dC      = 2^L;*)
(*  idxFull = Compile[{{q1,_Integer},{c,_Integer},{q2,_Integer},{dC,_Integer}},*)
(*              q1*(2*dC) + c*2 + q2 + 1,*)
(*              CompilationTarget -> $CompileTarget];*)
(*  getCols[q1_, q2_] := Table[idxFull[q1, c, q2, dC], {c, 0, dC - 1}];*)
(*  ParallelTable[*)
(*    Conjugate[U[[All, getCols[q1, q2]]]] . Transpose[U[[All, getCols[q1p, q2p]]]],*)
(*    {q1, 0, 1}, {q2, 0, 1}, {q1p, 0, 1}, {q2p, 0, 1}]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 12 -- K-matrix builder                                     *)*)
(*(*                                                                   *)*)
(*(* Absorbs a D_total x D_total energy-basis operator into Tmat via  *)*)
(*(* Hadamard product; flattens to a (4 x 4 x D^2) array.            *)*)
(*(* ================================================================ *)*)
(*Clear[BuildKMatrix];*)
(*BuildKMatrix[\[Rho]E_, T_] := ArrayReshape[*)
(*  Table[*)
(*    Flatten[\[Rho]E * T[[q1+1, q2+1, q1p+1, q2p+1]]],*)
(*    {q1, 0, 1}, {q2, 0, 1}, {q1p, 0, 1}, {q2p, 0, 1}],*)
(*  {4, 4, Length[\[Rho]E]^2}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 13 -- Energy difference vector                             *)*)
(*(*                                                                   *)*)
(*(* Flattened D^2 vector of all E_alpha - E_beta.                    *)*)
(*(* Depends only on Eval. Built ONCE per (L, delta).                  *)*)
(*(* ================================================================ *)*)
(*Clear[BuildEnergyDiffs];*)
(*BuildEnergyDiffs[E_] := Flatten[Outer[Subtract, E, E]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 14 -- Per-step contraction                                 *)*)
(*(*                                                                   *)*)
(*(* Kmat (4 x 4 x D^2) dotted with the phase vector phi(t).         *)*)
(*(* Returns the 4 x 4 output block for one (i,j) input pair.         *)*)
(*(* ================================================================ *)*)
(*Clear[ComputeRhoAB];*)
(*ComputeRhoAB[Kmat_, dEflat_, t_?NumericQ] :=*)
(*  Kmat . Exp[(-I) * dEflat * t];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 15 -- Edge column blocks                                   *)*)
(*(*                                                                   *)*)
(*(* Returns {U1,U2,U3,U4}: D_total x dC submatrices of Evec,         *)*)
(*(* s in 1..4 <-> (q1,q2) with q1 = high bit, q2 = low bit.          *)*)
(*(* Depends only on Evec and L. Built ONCE per (L, delta).            *)*)
(*(* Reused across all beta values for that (L, delta).               *)*)
(*(* ================================================================ *)*)
(*Clear[EdgeColumnBlocks];*)
(*EdgeColumnBlocks[Evec_, L_] := Module[*)
(*  {dC = 2^L, idxFull, getCols},*)
(*  idxFull = Compile[{{q1,_Integer},{c,_Integer},{q2,_Integer},{dC,_Integer}},*)
(*               q1*(2*dC) + c*2 + q2 + 1,*)
(*               CompilationTarget -> $CompileTarget];*)
(*  getCols[q1_, q2_] := Table[idxFull[q1, c, q2, dC], {c, 0, dC - 1}];*)
(*  Table[*)
(*    Evec[[All, getCols[Quotient[s - 1, 2], Mod[s - 1, 2]]]],*)
(*    {s, 1, 4}]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 16 -- Per-(i,j) K-matrices for the Choi construction      *)*)
(*(*                                                                   *)*)
(*(* M_ij = Conj[Ucols[[i]]] . rhoChain . Transpose[Ucols[[j]]]       *)*)
(*(*   = energy-basis projection of |i><j| (x) rhoChain.              *)*)
(*(* Only i<=j built (10 of 16 pairs). Lower triangle filled by        *)*)
(*(* conjugate transpose at evaluation time -- exact, not approximate. *)*)
(*(*                                                                   *)*)
(*(* Signature change vs choi_methods_comparison.m: takes precomputed  *)*)
(*(* Ucols directly (not Evec, L) so the column extraction is not     *)*)
(*(* repeated across beta values.                                      *)*)
(*(* ================================================================ *)*)
(*Clear[BuildChoiKMatricesFast];*)
(*BuildChoiKMatricesFast[Ucols_, rhoChain_, T_] :=*)
(*  Table[*)
(*    If[i <= j,*)
(*      BuildKMatrix[Conjugate[Ucols[[i]]] . rhoChain . Transpose[Ucols[[j]]], T],*)
(*      Null],*)
(*    {i, 1, 4}, {j, 1, 4}];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 17 -- Choi matrix assembler at time t                     *)*)
(*(*                                                                   *)*)
(*(* Computes the 10 upper-triangle blocks via ComputeRhoAB, fills     *)*)
(*(* the lower 6 by conjugate transpose, stacks into dS^2 x dS^2     *)*)
(*(* Choi matrix.                                                      *)*)
(*(* ================================================================ *)*)
(*Clear[ComputeChoiMatrixFast];*)
(*ComputeChoiMatrixFast[Kmat_, dEflat_, t_?NumericQ, dS_Integer] := Module[*)
(*  {upper, blocks},*)
(*  upper = Table[*)
(*    If[i <= j, Chop[ComputeRhoAB[Kmat[[i, j]], dEflat, t]], Null],*)
(*    {i, 1, 4}, {j, 1, 4}];*)
(*  blocks = Table[*)
(*    If[i <= j, upper[[i, j]], ConjugateTranspose[upper[[j, i]]]],*)
(*    {i, 1, 4}, {j, 1, 4}];*)
(*  PackedC[ArrayFlatten[blocks] / dS]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 18 -- Fast Choi channel closure                            *)*)
(*(*                                                                   *)*)
(*(* Returns Function[t, chi(t)]. Same interface as ChoiChannelF so   *)*)
(*(* ChoiSeries works unchanged.                                       *)*)
(*(* ================================================================ *)*)
(*Clear[BuildChoiFnFast];*)
(*BuildChoiFnFast[KmatIn_, dEflatIn_, dSIn_Integer] := Module[*)
(*  {Kmat = KmatIn, dEflat = dEflatIn, dS = dSIn},*)
(*  Function[{t}, ComputeChoiMatrixFast[Kmat, dEflat, t, dS]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 19 -- MakePlotsChoiThermal                                 *)*)
(*(*                                                                   *)*)
(*(* Generates exactly two PNG files and one .mx per (L, kDelta, beta).*)*)
(*(*                                                                   *)*)
(*(* Plot 1 -- ChoiObservables_D<kk>_<betastr>.png                     *)*)
(*(*   Purity Tr[chi^2] (black) and VNEntropy S(chi) (blue) together.  *)*)
(*(*   Reference lines: 1/dS^2 (red dashed) for the depolarizing lower *)*)
(*(*   bound on purity, log(dS^2) (green dashed) for entropy upper     *)*)
(*(*   bound; both correspond to the maximally mixed channel.           *)*)
(*(*                                                                   *)*)
(*(* Plot 2 -- ChoiEigenvalues5_D<kk>_<betastr>.png                    *)*)
(*(*   First 5 eigenvalues of chi(t), sorted descending.               *)*)
(*(*                                                                   *)*)
(*(* Binary data -- choi_data_D<kk>_<betastr>.mx                       *)*)
(*(* ================================================================ *)*)
(*MakePlotsChoiThermal[results_, LL_, kDelta_, beta_, dS_, dE_, dir_] := Module[*)
(*  {delta, label, ext, get, commonOpts,*)
(*   purityTS, entropyTS, nEVals, evSeries, evColors, evStyles, evLabels},*)
(**)
(*  delta = N[kDelta / 10];*)
(*  label = "XXZ edge-spin Choi,  L=" <> ToString[LL] <>*)
(*          ",  \[CapitalDelta]=" <> ToString[NumberForm[delta, {3,1}]] <>*)
(*          ",  " <> BetaLabel[beta] <>*)
(*          ",  dS=" <> ToString[dS];*)
(*  ext   = "_D" <> StringPadLeft[ToString[kDelta], 2, "0"] <>*)
(*          "_"  <> BetaStr[beta] <> ".png";*)
(**)
(*  get[key_] := {#["Time"], #[key]} & /@ results;*)
(**)
(*  commonOpts = Sequence[*)
(*    Frame      -> True,*)
(*    LabelStyle -> Directive[Black, 16],*)
(*    PlotLabel  -> Style[label, Black, 13],*)
(*    ImageSize  -> 700,*)
(*    PlotRange  -> All];*)
(**)
(*  (* --- Plot 1: Choi Observables --- *)*)
(*  purityTS  = get["Purity"];*)
(*  entropyTS = get["VNEntropy"];*)
(*  Export[FileNameJoin[{dir, "ChoiObservables" <> ext}],*)
(*    Show[*)
(*      ListLinePlot[*)
(*        {purityTS, entropyTS},*)
(*        FrameLabel  -> {"Time (t)", "Choi Observables"},*)
(*        PlotStyle   -> {Directive[Thick, Black], Directive[Thick, Blue]},*)
(*        PlotLegends -> Placed[LineLegend[*)
(*          {Directive[Thick, Black], Directive[Thick, Blue]},*)
(*          {"Purity Tr[\[ScriptCapitalE]^2]", "Entropy S(\[ScriptCapitalE])"},*)
(*          LegendFunction -> Framed], Right],*)
(*        commonOpts],*)
(*      Plot[1/dS^2, {t, 0, tMax},*)
(*        PlotStyle -> Directive[Red, Dashed, Thick]],*)
(*      Plot[Log[dS^2], {t, 0, tMax},*)
(*        PlotStyle -> Directive[Darker[Green], Dashed, Thick]]]];*)
(**)
(*  (* --- Plot 2: First 5 eigenvalues of chi(t) --- *)*)
(*  nEVals   = 5;*)
(*  evSeries = ExtractEVals[results, nEVals];*)
(*  evColors = {Black, Red, Blue, Darker[Green], Orange};*)
(*  evStyles = Directive[#, Thick] & /@ evColors;*)
(*  evLabels = Table[Style["\[Lambda]" <> ToString[kk2], 15], {kk2, 1, nEVals}];*)
(*  Export[FileNameJoin[{dir, "ChoiEigenvalues5" <> ext}],*)
(*    ListLinePlot[evSeries,*)
(*      FrameLabel  -> {"Time (t)", "\[Lambda]k(\[ScriptCapitalE](t))"},*)
(*      PlotStyle   -> evStyles,*)
(*      PlotLegends -> Placed[LineLegend[evColors, evLabels,*)
(*                       LegendLayout -> "Column"], Right],*)
(*      commonOpts]];*)
(**)
(*  (* --- Binary data export --- *)*)
(*  Export[FileNameJoin[{dir,*)
(*    "choi_data_D" <> StringPadLeft[ToString[kDelta], 2, "0"] <>*)
(*    "_" <> BetaStr[beta] <> ".mx"}],*)
(*    results];*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* Distribute stable definitions to parallel kernels once.          *)*)
(*(* choiFnFast (closure, changes per beta) is distributed inside     *)*)
(*(* the beta loop.                                                    *)*)
(*(* ================================================================ *)*)
(*DistributeDefinitions[*)
(*  PackedC, ComputeRhoAB, ComputeChoiMatrixFast, BuildChoiFnFast,*)
(*  ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs,*)
(*  ExtractTS, ExtractEVals*)
(*];*)


(* ::Chapter::Closed:: *)
(*Fixed Parameters*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODEL SPECIFICATION -- evaluate this entire cell at once.        *)*)
(*(*                                                                   *)*)
(*(* Chain model: XXZwLocalDefectHamiltonian[Jxy, Jz, w, ed, L, d]    *)*)
(*(*   with defect terms off (w=ed=0) -> clean XXZ chain.              *)*)
(*(*   Jz = delta = \[CapitalDelta]/10. (fixed; not swept in this file).               *)*)
(*(*                                                                   *)*)
(*(* kDelta = IntegerPart[\[CapitalDelta]] is the integer key for file naming:          *)*)
(*(*   delta=1.0 -> \[CapitalDelta]=10 -> kDelta=10 -> suffix _D10.                    *)*)
(*(*   File suffix format is identical to choi_edge_spins.m.           *)*)
(*(* ================================================================ *)*)
(*{\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = {1., 1., 0.1, 0.1};*)
(*{Jxy, w, ed}              = {1., 0, 0};*)
(*\[CapitalDelta]                       = 10;            (* delta = 1.0 *)*)
(*kDelta                    = IntegerPart[\[CapitalDelta]];*)
(**)
(*tMax  = 50.;*)
(*dt    = 0.1;*)
(*tlist = Range[0., tMax, dt];*)
(**)
(*HAlocal   = \[CapitalDelta]a * \[Sigma]z;*)
(*HBlocal   = \[CapitalDelta]b * \[Sigma]z;*)
(*couplingA = {{\[Lambda]a, \[Sigma]p, \[Sigma]m}, {\[Lambda]a, \[Sigma]m, \[Sigma]p}};*)
(*couplingB = {{\[Lambda]b, \[Sigma]p, \[Sigma]m}, {\[Lambda]b, \[Sigma]m, \[Sigma]p}};*)
(**)
(*dS = 4;   (* S = Q1 x Q2; fixed for two spin-1/2 edge spins *)*)
(**)
(*betaList = {0.,0.5, 1., 10.,Infinity};*)
(*LList    = Range[3,6];*)
(**)
(*baseDir = NotebookDirectory[];*)
(**)
(*Print["Fixed parameters set:"];*)
(*Print["  {\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = ", {\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b}];*)
(*Print["  {Jxy, w, ed} = ", {Jxy, w, ed}, "   (defect off when w=ed=0)"];*)
(*Print["  delta = ", N[\[CapitalDelta]/10], "   (kDelta = ", kDelta, ")"];*)
(*Print["  dS = ", dS, "   tMax = ", tMax, "   dt = ", dt,*)
(*       "   steps = ", Length[tlist]];*)
(*Print["  LList = ", LList];*)
(*Print["  betaList = ", betaList];*)
(*Print["  Total runs = ", Length[LList] * Length[betaList]];*)


(* ::Chapter:: *)
(*Sweep*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* Outer loop: L                                                     *)*)
(*(* Inner loop: beta                                                  *)*)
(*(*                                                                   *)*)
(*(* Per L:                                                             *)*)
(*(*   1. Build Ha and HT in [Q1,Chain,Q2] layout.                     *)*)
(*(*   2. Diagonalize -> {Eval, Evec}.                                  *)*)
(*(*   3. BuildTransferTensors(Evec, L) -> Tmat.       (beta-invariant) *)*)
(*(*   4. EdgeColumnBlocks(Evec, L)     -> Ucols.      (beta-invariant) *)*)
(*(*   5. BuildEnergyDiffs(Eval)        -> dEflat.     (beta-invariant) *)*)
(*(*   Clear Evec (no longer needed after steps 3-5).                  *)*)
(*(*                                                                   *)*)
(*(* Per (L, beta):                                                     *)*)
(*(*   6.  ThermalChainState(Ha, beta) -> rhoChain.                     *)*)
(*(*   7.  BuildChoiKMatricesFast(Ucols, rhoChain, Tmat) -> KmatFast.   *)*)
(*(*   8.  BuildChoiFnFast(KmatFast, dEflat, dS) -> choiFnFast.         *)*)
(*(*   9.  Sanity check at t=0: Tr[chi^2]=1, Tr[chi]=1, dim = dS^2 x dS^2. *)*)
(*(*  10.  DistributeDefinitions[choiFnFast, ...] to parallel workers.  *)*)
(*(*  11.  ChoiSeries -> choiResults.                                    *)*)
(*(*  12.  MakePlotsChoiThermal -> 2 PNG + 1 .mx.                        *)*)
(*(*                                                                   *)*)
(*(* Memory: Evec cleared after step 5; rhoChain after step 7;         *)*)
(*(* KmatFast after step 8 (absorbed into choiFnFast closure);          *)*)
(*(* choiFnFast and choiResults cleared at end of each beta step.       *)*)
(*(* Ha, Tmat, Ucols, dEflat, Eval cleared at end of each L step.       *)*)
(*(* ================================================================ *)*)
(**)


(* ::Input:: *)
(*kDeltaList = {0.,1.0,10.};   (* integer keys: delta = k/10, exact values *)*)


(* ::Input:: *)
(*Do[*)
(*Do[*)
(*kDelta=k;*)
(*LL = IntegerPart[L];*)
(*dE = 2^LL;*)
(**)
(*  dirL    = FileNameJoin[{baseDir, "L=" <> ToString[LL]}];*)
(*  dirChoi = FileNameJoin[{dirL, "Choi"}];*)
(*  If[!DirectoryQ[dirL],    CreateDirectory[dirL]];*)
(*  If[!DirectoryQ[dirChoi], CreateDirectory[dirChoi]];*)
(**)
(*  Print["=== L = ", LL, "  dE = ", dE, "  D_total = ", dS*dE, " ==="];*)
(**)
(*  (* --- Per-L: Hamiltonian and beta-invariant precomputed objects --- *)*)
(*  Ha           = XXZwLocalDefectHamiltonian[Jxy, N[kDelta/10], w, ed, LL, LL];*)
(*  HT           = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal,*)
(*                       couplingA, couplingB, LL]];*)
(*  {Eval, Evec} = DiagonalizeH[HT];*)
(*  Clear[HT];*)
(*  Print["  Evec: ", Dimensions[Evec],*)
(*        "  (expected {", dS*dE, ", ", dS*dE, "})"];*)
(**)
(*  Tmat   = BuildTransferTensors[Evec, LL];*)
(*  Ucols  = EdgeColumnBlocks[Evec, LL];*)
(*  dEflat = BuildEnergyDiffs[Chop[Eval]];*)
(*  Clear[Evec];*)
(*  Print["  Tmat and Ucols built."];*)
(**)
(*  (* --- Beta loop --- *)*)
(*  Do[*)
(*    beta = betaList[[ib]];*)
(*    Print["  \[Beta] = ", BetaLabel[beta], "   ..."];*)
(*    t0 = AbsoluteTime[];*)
(**)
(*    rhoChain = ThermalChainState[Ha, beta];*)
(*    Print["    Tr[rhoChain] = ", N@Re@Tr[rhoChain],*)
(*          "   min eigenvalue = ", N@Min[Re[Eigenvalues[rhoChain]]]];*)
(**)
(*    KmatFast   = BuildChoiKMatricesFast[Ucols, rhoChain, Tmat];*)
(*    Clear[rhoChain];*)
(*    (* choiFnFast is a PURE function referencing the GLOBAL symbols       *)*)
(*    (* KmatFast, dEflat, dS by name -- it captures no large array. The    *)*)
(*    (* old Module-closure (BuildChoiFnFast) localized Kmat into a fresh   *)*)
(*    (* Kmat$nnnn symbol on every call; because that symbol escaped via    *)*)
(*    (* the returned Function, Mathematica never garbage-collected it, so  *)*)
(*    (* each beta iteration leaked one full ~250 MB copy. The pure-function*)*)
(*    (* form below creates no such temporary; KmatFast is one fixed global *)*)
(*    (* that is OVERWRITTEN (and its old value freed) every iteration.     *)*)
(*    (* KmatFast is intentionally NOT cleared here -- the function needs it.*)*)
(*    choiFnFast = (ComputeChoiMatrixFast[KmatFast, dEflat, #, dS] &);*)
(**)
(*    (* Sanity check: chi(0) = |Omega><Omega| => Tr[chi^2] = 1 *)*)
(*    choi0 = choiFnFast[0.];*)
(*    Print["    t=0 check: Tr[chi^2] = ", ChoiPurity[choi0],*)
(*          "  Tr[chi] = ", N@Re@Tr[choi0],*)
(*          "  dim = ", Dimensions[choi0],*)
(*          "  (expected {", dS^2, ", ", dS^2, "})"];*)
(*    Clear[choi0];*)
(**)
(*    (* Distribute the DATA globals (KmatFast overwrites the previous copy *)*)
(*    (* on each worker -- same symbol name -- so workers do not accumulate).*)*)
(*    DistributeDefinitions[*)
(*      KmatFast, dEflat, dS, choiFnFast,*)
(*      PackedC, ComputeRhoAB, ComputeChoiMatrixFast,*)
(*      ChoiPurity, ChoiVNEntropy, ChoiEVals, ChoiAllObs*)
(*    ];*)
(**)
(*    AbsoluteTiming[*)
(*      choiResults = ChoiSeries[choiFnFast, tlist,*)
(*        "Observables" -> "All",*)
(*        "Parallel"    -> True];*)
(*    ];*)
(*    Clear[choiFnFast];*)
(**)
(*    MakePlotsChoiThermal[choiResults, LL, kDelta, beta, dS, dE, dirChoi];*)
(*    Clear[choiResults];*)
(**)
(*    Print["    done in ", Round[AbsoluteTime[] - t0, 0.1], " s"];*)
(**)
(*    , {ib, Length[betaList]}*)
(*  ];*)
(**)
(*  ParallelEvaluate[Clear[KmatFast, dEflat, choiFnFast]];*)
(*  ParallelEvaluate[ClearSystemCache[]];*)
(*  Clear[Ha, Tmat, Ucols, dEflat, Eval, KmatFast];*)
(**)
(**)
(*,{k,kDeltaList}];*)
(*  , {L, LList}*)
(*];*)
(**)
(*Print["Choi thermal sweep complete."];*)



