(* ::Package:: *)

(* ::Title::Closed:: *)
(*Setup*)


(* ::Input:: *)
(*SetDirectory[NotebookDirectory[]];*)


(* ::Input:: *)
(*Get["C:\\Users\\Miguel\\Github\\Spin transport\\Quantum channel\\QMB_offline.wl"];*)


(* ::Input:: *)
(*LaunchKernels[10];*)


(* ::Title::Closed:: *)
(*Efficient*)


(* ::Chapter::Closed:: *)
(*Definitions*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 0 \[LongDash] Kernel setup                                           *)*)
(*(* ================================================================ *)*)
(*(* Set compile target for all Compile calls in this session.        *)*)
(*(* Falls back to "WVM" automatically if no C compiler is found.     *)*)
(*$CompileTarget = "WVM";*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 1 \[LongDash] Compiled partial traces (hardcoded for 4x4 \[Rho]_AB)      *)*)
(*(*                                                                   *)*)
(*(* These are exact index operations on a 4x4 complex matrix.        *)*)
(*(* Layout assumed: rows/cols indexed as (q1,q2) \[Element] {00,01,10,11}.   *)*)
(*(* ================================================================ *)*)
(*Clear[TraceOutA,TraceOutB];*)
(*TraceOutB = Compile[                  (* keep spin A, trace out B *)*)
(*  {{\[Rho], _Complex, 2}},*)
(*  {{\[Rho][[1,1]] + \[Rho][[2,2]],  \[Rho][[1,3]] + \[Rho][[2,4]]},*)
(*   {\[Rho][[3,1]] + \[Rho][[4,2]],  \[Rho][[3,3]] + \[Rho][[4,4]]}},*)
(*  CompilationTarget -> $CompileTarget,*)
(*  RuntimeOptions -> "Speed"*)
(*];*)
(*TraceOutA = Compile[                  (* keep spin B, trace out A *)*)
(*  {{\[Rho], _Complex, 2}},*)
(*  {{\[Rho][[1,1]] + \[Rho][[3,3]],  \[Rho][[1,2]] + \[Rho][[3,4]]},*)
(*   {\[Rho][[2,1]] + \[Rho][[4,3]],  \[Rho][[2,2]] + \[Rho][[4,4]]}},*)
(*  CompilationTarget -> $CompileTarget,*)
(*  RuntimeOptions -> "Speed"*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 2 \[LongDash] Von Neumann entropy                                     *)*)
(*(*                                                                   *)*)
(*(* 2\[Times]2: compiled with analytical eigenvalues \[LongDash] no Eigenvalues call. *)*)
(*(* Eigenvalues of {{a,b},{c,d}} with a,d real and c=Conj[b]:        *)*)
(*(*   \[Lambda]_{1,2} = ((a+d) \[PlusMinus] sqrt((a-d)\.b2 + 4|b|\.b2)) / 2                  *)*)
(*(*                                                                   *)*)
(*(* 4\[Times]4: cannot be compiled \[LongDash] Eigenvalues[] is not compilable.       *)*)
(*(*  Called once per time step on a 4\[Times]4 matrix \[LongDash] cost is negligible. *)*)
(*(* ================================================================ *)*)
(*Clear[VNEntropy2x2,VNEntropy4x4];*)
(*VNEntropy2x2 = Compile[*)
(*  {{\[Rho], _Complex, 2}},*)
(*  Module[{r11, r22, r12r, r12i, absq, disc, \[Lambda]1, \[Lambda]2},*)
(*    r11  = Re[\[Rho][[1,1]]];*)
(*    r22  = Re[\[Rho][[2,2]]];*)
(*    r12r = Re[\[Rho][[1,2]]];*)
(*    r12i = Im[\[Rho][[1,2]]];*)
(*    absq = r12r^2 + r12i^2;               (* |\[Rho]12|\.b2 \[LongDash] never negative *)*)
(*    disc = Sqrt[(r11 - r22)^2 + 4.*absq]; (* sqrt arg always \[GreaterEqual] 0     *)*)
(*    \[Lambda]1   = (r11 + r22 + disc)/2.;*)
(*    \[Lambda]2   = (r11 + r22 - disc)/2.;*)
(*    If[\[Lambda]1 > 1.*^-14, -\[Lambda]1*Log[\[Lambda]1], 0.] +*)
(*    If[\[Lambda]2 > 1.*^-14, -\[Lambda]2*Log[\[Lambda]2], 0.]*)
(*  ],*)
(*  CompilationTarget -> $CompileTarget,*)
(*  RuntimeOptions -> "Speed"*)
(*];*)
(*VNEntropy4x4[\[Rho]_] := Module[*)
(*  {\[Lambda] = Select[Re[Eigenvalues[N[\[Rho]]]], # > 1.*^-14 &]},*)
(*  -\[Lambda] . Log[\[Lambda]]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 3 \[LongDash] Concurrence (Wootters 1998)                            *)*)
(*(*                                                                   *)*)
(*(* spinFlip = \[Sigma]y\[CircleTimes]\[Sigma]y is constant \[LongDash] precomputed once here as a        *)*)
(*(* packed numerical array so Dot calls use BLAS.                    *)*)
(*(* Eigenvalues on 4x4 is not compilable; the 4x4 call is trivial.   *)*)
(*(* ================================================================ *)*)
(*spinFlip = N[KroneckerProduct[PauliMatrix[2], PauliMatrix[2]]];*)
(**)
(*Clear[Concurrence];*)
(*Concurrence[\[Rho]_] := Module[*)
(*  {\[Rho]Tilde, \[Lambda]s},*)
(*  \[Rho]Tilde = spinFlip . Conjugate[\[Rho]] . spinFlip;*)
(*  \[Lambda]s     = Reverse[Sort[Re[Sqrt[Chop[Eigenvalues[\[Rho] . \[Rho]Tilde]]]]]];*)
(*  Max[0., \[Lambda]s[[1]] - \[Lambda]s[[2]] - \[Lambda]s[[3]] - \[Lambda]s[[4]]]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 4 \[LongDash] Single-pass observable aggregator                      *)*)
(*(*                                                                   *)*)
(*(* Takes the 4\[Times]4 \[Rho]_AB and a reference state \[Rho]_ref (for survival).  *)*)
(*(* All quantities computed in one pass over \[Rho]_AB \[LongDash] no redundancy.   *)*)
(*(* ================================================================ *)*)
(*Clear[ComputeAllObservables];*)
(*ComputeAllObservables[\[Rho]AB_, \[Rho]ref_] := Module[*)
(*  {\[Rho]A, \[Rho]B, SA, SB, SAB},*)
(*  \[Rho]A  = TraceOutB[\[Rho]AB];*)
(*  \[Rho]B  = TraceOutA[\[Rho]AB];*)
(*  SA  = VNEntropy2x2[\[Rho]A];*)
(*  SB  = VNEntropy2x2[\[Rho]B];*)
(*  SAB = VNEntropy4x4[\[Rho]AB];*)
(*  <|*)
(*    "Concurrence"  -> Concurrence[\[Rho]AB],*)
(*    "Purity"       -> Re[Tr[\[Rho]AB . \[Rho]AB]],*)
(*    "EntropyA"     -> SA,*)
(*    "EntropyB"     -> SB,*)
(*    "MutualInfo"   -> SA + SB - SAB,       (* I(A:B) = S(A)+S(B)-S(AB) *)*)
(*    "SpinSurvival" -> Re[Tr[\[Rho]ref . \[Rho]AB]]   (* valid for pure \[Rho]ref      *)*)
(*  |>*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 5 \[LongDash] Transfer tensor builder                                *)*)
(*(*                                                                   *)*)
(*(* Given eigenvector matrix U (rows = eigenvectors) and chain       *)*)
(*(* length L, returns a {2,2,2,2} array of (D\[Times]D) matrices where      *)*)
(*(*                                                                   *)*)
(*(*  T[[q1+1,q2+1,q1p+1,q2p+1]]_\[Alpha]\[Beta]                                  *)*)
(*(*    = \[CapitalSigma]_c Conj[U[[\[Alpha], idx(q1,c,q2)]]] * U[[\[Beta], idx(q1p,c,q2p)]]   *)*)
(*(*                                                                   *)*)
(*(* idx(q1,c,q2) is the linear index in the [Q1, Chain, Q2] layout. *)*)
(*(*                                                                   *)*)
(*(* In matrix form: T = Conj[U[:,colsA]] . Transpose[U[:,colsB]]    *)*)
(*(* \[LongDash] a (D\[Times]2^L)\[CenterDot](2^L\[Times]D) product using BLAS.                         *)*)
(*(*                                                                   *)*)
(*(* The 16 products are independent \[RightArrow] parallelize over them.         *)*)
(*(* ================================================================ *)*)
(*Clear[BuildTransferTensors];*)
(*BuildTransferTensors[U_, L_] := Module[*)
(*  {dC, idxFull, getCols},*)
(*  dC       = 2^L;*)
(*  idxFull  = Compile[{{q1,_Integer},{c,_Integer},{q2,_Integer},{dC,_Integer}},*)
(*               q1*(2*dC) + c*2 + q2 + 1,*)
(*               CompilationTarget -> $CompileTarget];*)
(*  getCols[q1_, q2_] := Table[idxFull[q1, c, q2, dC], {c, 0, dC - 1}];*)
(*  ParallelTable[*)
(*    Conjugate[U[[All, getCols[q1, q2]]]] . Transpose[U[[All, getCols[q1p, q2p]]]],*)
(*    {q1, 0, 1}, {q2, 0, 1}, {q1p, 0, 1}, {q2p, 0, 1}*)
(*  ]*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 6 \[LongDash] K-matrix builder                                       *)*)
(*(*                                                                   *)*)
(*(* Absorbs \[Rho]_E (energy-basis initial state) into the transfer       *)*)
(*(* tensors. Result shape: {4, 4, D\.b2}.                               *)*)
(*(*                                                                   *)*)
(*(*  K[[i,j,p]] = (\[Rho]_E \[CircleDot] T_ij)_flat[p]                              *)*)
(*(*                                                                   *)*)
(*(* At each time step: \[Rho]_AB(t) = K . phase_flat(t)  [4\[Times]4 matrix]    *)*)
(*(* This single BLAS call replaces all the per-step matrix work.     *)*)
(*(* ================================================================ *)*)
(*Clear[BuildKMatrix];*)
(*BuildKMatrix[\[Rho]E_, T_] := ArrayReshape[*)
(*  Table[*)
(*    Flatten[\[Rho]E * T[[q1+1, q2+1, q1p+1, q2p+1]]],*)
(*    {q1, 0, 1}, {q2, 0, 1}, {q1p, 0, 1}, {q2p, 0, 1}*)
(*  ],*)
(*  {4, 4, Length[\[Rho]E]^2}*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 7 \[LongDash] Energy difference vector and global survival vector    *)*)
(*(*                                                                   *)*)
(*(* dEflat[[\[Alpha]*(D)+\[Beta]]] = E_\[Alpha] - E_\[Beta]  (real packed array, length D\.b2)   *)*)
(*(*                                                                   *)*)
(*(* Gflat encodes the global survival probability as a dot product:  *)*)
(*(*  surv_global(t) = Re[ Gflat . Conj[phase_flat(t)] ]             *)*)
(*(*                                                                   *)*)
(*(* Derivation: Tr[\[Rho]0\[CenterDot]\[Rho](t)] = Tr[\[Rho]_E \[CenterDot] \[Rho]_E(t)]                     *)*)
(*(*  = \[CapitalSigma]_\[Alpha]\[Beta] \[Rho]_E_\[Alpha]\[Beta] \[CenterDot] \[Rho]_E_\[Beta]\[Alpha] \[CenterDot] e^{+i(E_\[Alpha]-E_\[Beta])t}                     *)*)
(*(*  = Gflat \[CenterDot] Conj[phase_flat]    (Conj because sign flips)         *)*)
(*(* ================================================================ *)*)
(*Clear[BuildEnergyDiffs,BuildGflat];*)
(*BuildEnergyDiffs[E_] := Flatten[Outer[Subtract, E, E]];   (* D\.b2-vector, real *)*)
(*BuildGflat[\[Rho]E_] := Flatten[\[Rho]E * Transpose[\[Rho]E]];           (* D\.b2-vector, complex *)*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 8 \[LongDash] Core per-step functions                                *)*)
(*(*                                                                   *)*)
(*(* These are the only functions called inside the time loop.        *)*)
(*(* ComputeRhoAB: one Exp on a packed array + one BLAS Dot.          *)*)
(*(* ComputeSurvivalGlobal: one Exp + one dot product (scalar result).*)*)
(*(* ================================================================ *)*)
(*Clear[ComputeRhoAB,ComputeSurvivalGlobal];*)
(*ComputeRhoAB[Kmat_, dEflat_, t_?NumericQ] :=*)
(*  Kmat . Exp[(-I) * dEflat * t];*)
(*ComputeSurvivalGlobal[Gflat_, dEflat_, t_?NumericQ] :=*)
(*  Re[Gflat . Conjugate[Exp[(-I) * dEflat * t]]];*)


(* ::Chapter::Closed:: *)
(*Hamiltonian and couplings*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 9 \[LongDash] Pauli operators                                        *)*)
(*(* Packed numerical arrays \[LongDash] no symbolic overhead anywhere          *)*)
(*(* ================================================================ *)*)
(*\[Sigma]x  = N[PauliMatrix[1]];*)
(*\[Sigma]y  = N[PauliMatrix[2]];*)
(*\[Sigma]z  = N[PauliMatrix[3]];*)
(*\[Sigma]p  = \[Sigma]x + I*\[Sigma]y;   (* raising  operator *)*)
(*\[Sigma]m  = \[Sigma]x - I*\[Sigma]y;   (* lowering operator *)*)
(*id2 = N[IdentityMatrix[2]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 10 \[LongDash] Hamiltonian embedding functions                       *)*)
(*(*                                                                   *)*)
(*(* All operators live in the full [Q1, Chain, Q2] Hilbert space.    *)*)
(*(* SparseArray identities keep construction memory-efficient.       *)*)
(*(* Normal[] called only once at diagonalization \[LongDash] not here.         *)*)
(*(* ================================================================ *)*)
(*Clear[SparseId,EmbedSpinA,EmbedSpinB,EmbedChain,EmbedChainSite];*)
(*SparseId[n_] := SparseArray[Band[{1, 1}] -> 1., {n, n}];*)
(**)
(*(* Embed a 2\[Times]2 operator at spin A position in the full space *)*)
(*EmbedSpinA[op_, L_] :=*)
(*  KroneckerProduct[op, SparseId[2^L], SparseId[2]];*)
(*(* Embed a 2\[Times]2 operator at spin B position in the full space *)*)
(*EmbedSpinB[op_, L_] :=*)
(*  KroneckerProduct[SparseId[2], SparseId[2^L], op];*)
(*(* Embed the full chain Hamiltonian block in the full space *)*)
(*EmbedChain[Ha_, L_] :=*)
(*  KroneckerProduct[SparseId[2], Ha, SparseId[2]];*)
(*(* Embed a 2\[Times]2 operator at site k (1-indexed) within the chain     *)*)
(*(* Useful for chain-internal interactions if building Ha manually   *)*)
(*EmbedChainSite[op_, k_, L_] :=*)
(*  KroneckerProduct[SparseId[2^(k - 1)], op, SparseId[2^(L - k)]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 11 \[LongDash] Boundary coupling constructors                        *)*)
(*(*                                                                   *)*)
(*(* Takes a list of {opLeft, opRight} pairs and coupling strength \[Lambda]. *)*)
(*(* Each pair contributes one term in the interaction Hamiltonian.   *)*)
(*(*                                                                   *)*)
(*(* couplingTerms format: a list of {opA, opChainEdge} pairs.        *)*)
(*(*                                                                   *)*)
(*(* Examples:                                                         *)*)
(*(*   Heisenberg: \[Lambda]*{{\[Sigma]x,\[Sigma]x},{\[Sigma]y,\[Sigma]y},{\[Sigma]z,\[Sigma]z}}                       *)*)
(*(*   Flip-flop:  \[Lambda]*{{\[Sigma]p,\[Sigma]m},{\[Sigma]m,\[Sigma]p}}                               *)*)
(*(*   Ising:      \[Lambda]*{{\[Sigma]z,\[Sigma]z}}                                        *)*)
(*(*                                                                   *)*)
(*(* A-chain couples spin A to the FIRST chain site.                  *)*)
(*(* B-chain couples spin B to the LAST  chain site.                  *)*)
(*(* ================================================================ *)*)
(*Clear[BuildCouplingAChain, BuildCouplingBChain];*)
(**)
(*BuildCouplingAChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    term[[2]],*)
(*    KroneckerProduct[term[[3]], SparseId[2^(L - 1)]],*)
(*    SparseId[2]*)
(*  ],*)
(*  {term, couplingTerms}*)
(*];*)
(**)
(*BuildCouplingBChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[*)
(*    SparseId[2],*)
(*    KroneckerProduct[SparseId[2^(L - 1)], term[[2]]],*)
(*    term[[3]]*)
(*  ],*)
(*  {term, couplingTerms}*)
(*];*)
(**)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 12 \[LongDash] Full Hamiltonian assembler and diagonalization        *)*)
(*(*                                                                   *)*)
(*(* Ha is passed as a precomputed 2^L \[Times] 2^L numerical matrix.        *)*)
(*(* The model (Ising, XXZ, ...) lives entirely inside Ha.            *)*)
(*(* The coupling topology lives in couplingA, couplingB.             *)*)
(*(* This is the ONLY place density is needed \[LongDash] for LAPACK.           *)*)
(*(* Returns {eigenvalues (D-vector), eigenvectors (D\[Times]D, rows=vecs)}  *)*)
(*(* ================================================================ *)*)
(*Clear[BuildFullHamiltonian,DiagonalizeH];*)
(*BuildFullHamiltonian[HAlocal_, Ha_, HBlocal_, couplingA_, couplingB_, L_] :=*)
(*  EmbedSpinA[HAlocal, L] +*)
(*  EmbedChain[Ha, L]        +*)
(*  EmbedSpinB[HBlocal, L]  +*)
(*  BuildCouplingAChain[couplingA, L] +*)
(*  BuildCouplingBChain[couplingB, L];*)
(**)
(*DiagonalizeH[HT_] := Transpose[Sort[Transpose[Eigensystem[Normal[N[HT]]]]]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 13 \[LongDash] Initial state construction                            *)*)
(*(*                                                                   *)*)
(*(* The Hamiltonian lives in [Q1, Chain, Q2] space.                  *)*)
(*(*                                                                   *)*)
(*(* CASE A \[LongDash] correlated spin state (Bell, Werner, etc.):             *)*)
(*(*   \[Rho]_AB \[CircleTimes] \[Rho]_chain builds naturally as [Q1,Q2,Chain].              *)*)
(*(*   Needs a tensor index permutation \[RightArrow] [Q1,Chain,Q2].              *)*)
(*(*   Done by reshaping to rank-6, transposing, reshaping back.      *)*)
(*(*   Pure index operation \[LongDash] ZERO arithmetic.                         *)*)
(*(*                                                                   *)*)
(*(* CASE B \[LongDash] fully factored \[Rho]_A \[CircleTimes] \[Rho]_chain \[CircleTimes] \[Rho]_B:                    *)*)
(*(*   KroneckerProduct in this order directly gives [Q1,Chain,Q2].   *)*)
(*(*   NO permutation needed.                                          *)*)
(*(* ================================================================ *)*)
(*(* Tensor permutation [Q1,Q2,Chain] \[RightArrow] [Q1,Chain,Q2]                *)*)
(*(* Rank-6 index map: {q1,q2,c,q1',q2',c'} \[RightArrow] {q1,c,q2,q1',c',q2'} *)*)
(*(* Transpose argument: position k gets the index that was at perm[k]*)*)
(*Clear[PermuteToQ1ChainQ2,BuildInitialStateCorrelated,BuildInitialStateProduct];*)
(*PermuteToQ1ChainQ2[\[Rho]_, L_] := Module[{dC = 2^L},*)
(*  ArrayReshape[*)
(*    Transpose[*)
(*      ArrayReshape[\[Rho], {2, 2, dC, 2, 2, dC}],*)
(*      {1, 3, 2, 4, 6, 5}*)
(*    ],*)
(*    {4*dC, 4*dC}*)
(*  ]*)
(*];*)
(*(* Case A: spin state correlated (4\[Times]4) + chain state (2^L \[Times] 2^L)   *)*)
(*BuildInitialStateCorrelated[\[Rho]AB_, \[Rho]chain_, L_] :=*)
(*  PermuteToQ1ChainQ2[N[KroneckerProduct[\[Rho]AB, \[Rho]chain]], L];*)
(*(* Case B: fully factored \[LongDash] no permutation                          *)*)
(*BuildInitialStateProduct[\[Rho]A_, \[Rho]chain_, \[Rho]B_] :=*)
(*  N[KroneckerProduct[\[Rho]A, \[Rho]chain, \[Rho]B]];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 14 \[LongDash] Energy basis projection                               *)*)
(*(* \[Rho]_E = U \[CenterDot] \[Rho]0 \[CenterDot] U\[Dagger]                                                *)*)
(*(* ================================================================ *)*)
(*Clear[ProjectToEnergyBasis];*)
(*ProjectToEnergyBasis[U_, \[Rho]0_] := U . \[Rho]0 . ConjugateTranspose[U];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* DISTRIBUTE \[LongDash] send all definitions to parallel kernels            *)*)
(*DistributeDefinitions[*)
(*  \[Sigma]x, \[Sigma]y, \[Sigma]z, \[Sigma]p, \[Sigma]m, id2, spinFlip,*)
(*  TraceOutA, TraceOutB, VNEntropy2x2, VNEntropy4x4, Concurrence,*)
(*  ComputeAllObservables, ComputeRhoAB, ComputeSurvivalGlobal*)
(*];*)


(* ::Chapter::Closed:: *)
(*Parameters*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODEL + STATE SPECIFICATION                                      *)*)
(*(* This is the only block you change between runs.                  *)*)
(*(* ================================================================ *)*)
(*(* --- System size and time grid --- *)*)
(*L    = 8;*)


(* ::Input:: *)
(*{\[CapitalDelta]a,\[CapitalDelta]b,\[Lambda]a,\[Lambda]b}={1,1,0.35,0.35};*)


(* ::Input:: *)
(*(* --- Local Hamiltonians for the two system spins ---             *)*)
(*HAlocal = \[CapitalDelta]a * \[Sigma]z;       (* 2\[Times]2, field on spin A *)*)
(*HBlocal = \[CapitalDelta]b * \[Sigma]z;       (* 2\[Times]2, field on spin B *)*)
(*(* --- Boundary coupling terms ---                                  *)*)
(*(* Format: list of {opLeft, opRight} pairs, scaled by \[Lambda]            *)*)
(*(* Each pair becomes one term in the interaction Hamiltonian.      *)*)
(*couplingA={{\[Lambda]a,\[Sigma]p,\[Sigma]m},{\[Lambda]a,\[Sigma]m,\[Sigma]p}};*)
(*couplingB={{\[Lambda]b,\[Sigma]p,\[Sigma]m},{\[Lambda]b,\[Sigma]m,\[Sigma]p}};(* flip-flop chain\[LeftRightArrow]B  *)*)


(* ::Input:: *)
(*?OpenXXZHamiltonian*)


(* ::Input:: *)
(*{\[CapitalDelta],h1,h2}={5.,0.9,1.1};*)


(* ::Input:: *)
(*(* --- Chain Hamiltonian (your choice of model) ---               *)*)
(*(* Pass a precomputed numerical 2^L \[Times] 2^L matrix.                  *)*)
(*(* Example: XXZ chain with anisotropy \[CapitalDelta], boundary fields h1, h2    *)*)
(*Ha = OpenXXZHamiltonian[L,\[CapitalDelta],h1,h2];*)


(* ::Input:: *)
(*(* --- Build and diagonalize the full Hamiltonian --- *)*)
(*HT             = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal, couplingA, couplingB, L]];*)
(*{Eval, Evec}   = DiagonalizeH[HT];*)


(* ::Input:: *)
(*MeanLevelSpacingRatio[Sort[Chop[Eval]]]*)


(* ::Input:: *)
(*Histogram[Differences[Sort[Chop[Eval]]],PlotRange->All]*)


(* ::Input:: *)
(*(* --- Initial state --- *)*)
(*(* Option A: Bell state on spins, coherent state on chain          *)*)
(*bellState = {1, 0, 0, 1} / Sqrt[2.];*)
(*rhoAB     = Outer[Times, bellState, Conjugate[bellState]];*)
(*rhoChain  = Dyad[coherentstate[qubit[0., 0], L]];*)
(*rho0      = BuildInitialStateCorrelated[rhoAB, rhoChain, L];*)
(*(* reference for spin survival *)*)
(*rhoABref  = rhoAB;*)


(* ::Input:: *)
(*(* Option B: fully factored state \[LongDash] swap the two lines above with: *)*)
(*(* rho0     = BuildInitialStateProduct[rhoA, rhoChain, rhoB];      *)*)
(*(* rhoABref = KroneckerProduct[rhoA, rhoB];                        *)*)


(* ::Chapter::Closed:: *)
(*Method*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 15 \[LongDash] Precomputation sequence                               *)*)
(*(* Required inputs already defined upstream:                        *)*)
(*(*   {Eval, Evec}  from DiagonalizeH[HT]                           *)*)
(*(*   rho0          from BuildInitialState(Correlated|Product)[...]  *)*)
(*(*   rhoABref      4\[Times]4 reference spin state (for survival)         *)*)
(*(*                 = rhoAB for correlated case                      *)*)
(*(*                 = KroneckerProduct[rhoA, rhoB] for product case  *)*)
(*(* ================================================================ *)*)
(*Clear[rhoE,Tmat,Kmat,dEflat,Gflat];*)
(*rhoE   = ProjectToEnergyBasis[Evec, rho0];      (* D\[Times]D, computed ONCE    *)*)
(*Tmat   = BuildTransferTensors[Evec, L];          (* {2,2,2,2} of D\[Times]D mats *)*)
(*Kmat   = BuildKMatrix[rhoE, Tmat];               (* {4,4,D\.b2} \[LongDash] core object *)*)
(**)
(*Clear[Tmat];                                     (* no longer needed       *)*)
(*dEflat = BuildEnergyDiffs[Chop[Eval]];                 (* D\.b2-vector, real        *)*)
(*Gflat  = BuildGflat[rhoE];                      (* D\.b2-vector, complex     *)*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 16 \[LongDash] Distribute heavy objects to parallel kernels          *)*)
(*(*                                                                   *)*)
(*(* Done explicitly AFTER precomputation so workers receive the      *)*)
(*(* final packed arrays directly.                                    *)*)
(*(* DistributedContexts -> None in the loop avoids a second          *)*)
(*(* automatic distribution pass on every ParallelTable call.         *)*)
(*(*                                                                   *)*)
(*(* Memory note: each worker receives its own copy of Kmat.          *)*)
(*(*   L=7  (D=512)  \[RightArrow] ~32 MB \[Times] n_kernels                            *)*)
(*(*   L=9  (D=2048) \[RightArrow] ~512 MB \[Times] n_kernels  \[LeftArrow] verify RAM before use  *)*)
(*(* ================================================================ *)*)
(*DistributeDefinitions[*)
(*  Kmat, dEflat, Gflat, rhoABref,*)
(*  spinFlip,*)
(*  TraceOutA, TraceOutB,*)
(*  VNEntropy2x2, VNEntropy4x4,*)
(*  Concurrence,*)
(*  ComputeAllObservables,*)
(*  ComputeRhoAB,*)
(*  ComputeSurvivalGlobal*)
(*];*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 17 \[LongDash] Time evolution loop                                   *)*)
(*(* Per step cost:                                                    *)*)
(*(*   1. Exp on D\.b2-vector    \[RightArrow] packed array op, no loop              *)*)
(*(*   2. Kmat . phaseVec     \[RightArrow] BLAS (4\[Times]4\[Times]D\.b2)\[CenterDot](D\.b2) = 4\[Times]4 matrix      *)*)
(*(*   3. All observables     \[RightArrow] from 4\[Times]4 \[Rho]AB only                     *)*)
(*(*                                                                   *)*)
(*(* tMax and dt are free parameters \[LongDash] set them before this block.    *)*)
(*(* ================================================================ *)*)
(*tMax=100.;*)
(*dt=0.1;*)
(*tlist = Range[0., tMax, dt];                (* set tMax, dt upstream *)*)
(**)
(*AbsoluteTiming[allResults = ParallelTable[*)
(*  Module[{rhoAB, survGlobal, obs},*)
(*    rhoAB      = Chop[ComputeRhoAB[Kmat, dEflat, t]];*)
(*    survGlobal = ComputeSurvivalGlobal[Gflat, dEflat, t];*)
(*    obs        = ComputeAllObservables[rhoAB, rhoABref];*)
(*    Join[<|"Time" -> t, "SurvivalGlobal" -> survGlobal|>, obs]*)
(*  ],*)
(*  {t, tlist},*)
(*  DistributedContexts -> None        (* already distributed in Block 16 *)*)
(*];]*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* BLOCK 18 \[LongDash] Result extraction                                     *)*)
(*(* allResults is a list of Associations, one per time step.         *)*)
(*(* Available keys:                                                   *)*)
(*(*   "Time", "SurvivalGlobal",                                      *)*)
(*(*   "Concurrence", "Purity",                                       *)*)
(*(*   "EntropyA", "EntropyB", "MutualInfo", "SpinSurvival"           *)*)
(*(* ================================================================ *)*)
(*Clear[ExtractTimeSeries];*)
(*ExtractTimeSeries[key_] :=*)
(*  {#["Time"], #[key]} & /@ allResults;*)


(* ::Chapter::Closed:: *)
(*Results*)


(* ::Input:: *)
(*allResults[[1]]*)
(*(* <| "Time" -> 0., "SurvivalGlobal" -> 1., "Concurrence" -> 1., *)
(*      "Purity" -> 1., "EntropyA" -> 0., "EntropyB" -> 0., *)
(*      "MutualInfo" -> 0., "SpinSurvival" -> 1. |> *)*)


(* ::Input:: *)
(*(* ExtractTimeSeries["key"] gives {{t0,v0},{t1,v1},...} ready to plot *)*)
(*ListLinePlot[ExtractTimeSeries["Concurrence"],*)
(*  Frame -> True, FrameLabel -> {"Time (t)", "Concurrence"},*)
(*LabelStyle->Directive[Black,20],*)
(*  PlotStyle -> {Thick, Red}, ImageSize -> 600]*)
(**)
(*ListLinePlot[ExtractTimeSeries["SpinSurvival"],*)
(*  Frame -> True, FrameLabel -> {"Time (t)", "1st Spin Survival"},*)
(*LabelStyle->Directive[Black,20],*)
(*  PlotStyle -> {Thick, Blue}, ImageSize -> 600,PlotRange->All]*)
(**)
(*ListLinePlot[ExtractTimeSeries["MutualInfo"],*)
(*  Frame -> True, FrameLabel -> {"Time (t)", "Mutual Information"},*)
(*LabelStyle->Directive[Black,20],*)
(*  PlotStyle -> {Thick, Purple}, ImageSize -> 600,PlotRange->All]*)


(* ::Input:: *)
(*ListLinePlot[*)
(*  {ExtractTimeSeries["SpinSurvival"],*)
(*   ExtractTimeSeries["Concurrence"],*)
(*   ExtractTimeSeries["Purity"],*)
(*   ExtractTimeSeries["EntropyA"],*)
(*   ExtractTimeSeries["EntropyB"],*)
(*   ExtractTimeSeries["MutualInfo"]},*)
(*  Frame -> True,*)
(*  FrameLabel -> {"Time (t)", "Observables"},*)
(*  LabelStyle -> Directive[Black, 16],*)
(*  PlotStyle -> {*)
(*    Directive[Thick, Blue],*)
(*    Directive[Thick, Red],*)
(*    Directive[Thick, Darker[Green], Dashed],*)
(*    Directive[Thick, Orange],*)
(*    Directive[Thick, Purple],*)
(*    Directive[Thick, Darker[Red], DotDashed]*)
(*  },*)
(*  PlotLegends -> Placed[*)
(*    LineLegend[*)
(*      {"Spin Survival", "Concurrence", "Purity",*)
(*       "Entropy A", "Entropy B", "Mutual Info"},*)
(*      LegendFunction -> Framed*)
(*    ],*)
(*    Right*)
(*  ],*)
(*  ImageSize -> 700*)
(*]*)


(* ::Input:: *)
(*ListLinePlot[*)
(*  {ExtractTimeSeries["SpinSurvival"],*)
(*   ExtractTimeSeries["Concurrence"],*)
(*   ExtractTimeSeries["Purity"],*)
(*   ExtractTimeSeries["EntropyA"],*)
(*   ExtractTimeSeries["EntropyB"],*)
(*   ExtractTimeSeries["MutualInfo"]},*)
(*  Frame -> True,*)
(*  FrameLabel -> {"Time (t)", "Observables"},*)
(*  LabelStyle -> Directive[Black, 16],*)
(*  PlotStyle -> {*)
(*    Directive[Thick, Blue],*)
(*    Directive[Thick, Red],*)
(*    Directive[Thick, Darker[Green], Dashed],*)
(*    Directive[Thick, Orange],*)
(*    Directive[Thick, Purple],*)
(*    Directive[Thick, Darker[Red], DotDashed]*)
(*  },*)
(*  PlotLegends -> Placed[*)
(*    LineLegend[*)
(*      {"Spin Survival", "Concurrence", "Purity",*)
(*       "Entropy A", "Entropy B", "Mutual Info"},*)
(*      LegendFunction -> Framed*)
(*    ],*)
(*    Right*)
(*  ],*)
(*  ImageSize -> 700*)
(*]*)


(* ::Title::Closed:: *)
(*Cycle \[CapitalDelta], and size L*)


(* ::Input:: *)
(*(* ---------------------------------------------------------------- *)*)
(*(* MakePlots: generate and export all PNGs for one (L, k) run      *)*)
(*(* Filenames: Observable_D07.png  inside  baseDir/L=5/             *)*)
(*(* ---------------------------------------------------------------- *)*)
(*MakePlots[results_, L_, k_, dir_] := Module[*)
(*  {delta, label, ext, get, commonOpts},*)
(**)
(*  delta = N[k/10];*)
(*  label = "XXZ,  L = " <> ToString[L] <>*)
(*          ",  \[CapitalDelta] = " <> ToString[NumberForm[delta, {3, 1}]] <>*)
(*          ",  h1 = " <> ToString[h1sweep] <>*)
(*          ",  h2 = " <> ToString[h2sweep];*)
(*  ext   = "_D" <> StringPadLeft[ToString[k], 2, "0"] <> ".png";*)
(**)
(*  get[key_] := {#["Time"], #[key]} & /@ results;*)
(**)
(*  commonOpts = Sequence[*)
(*    Frame      -> True,*)
(*    LabelStyle -> Directive[Black, 16],*)
(*    PlotLabel  -> Style[label, Black, 13],*)
(*    ImageSize  -> 700,*)
(*    PlotRange  -> All*)
(*  ];*)
(**)
(*  Export[FileNameJoin[{dir, "Concurrence"    <> ext}],*)
(*    ListLinePlot[get["Concurrence"],*)
(*      FrameLabel -> {"Time (t)", "Concurrence"},*)
(*      PlotStyle  -> {Thick, Red},           commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "SpinSurvival"   <> ext}],*)
(*    ListLinePlot[get["SpinSurvival"],*)
(*      FrameLabel -> {"Time (t)", "Spin Survival"},*)
(*      PlotStyle  -> {Thick, Blue},          commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "MutualInfo"     <> ext}],*)
(*    ListLinePlot[get["MutualInfo"],*)
(*      FrameLabel -> {"Time (t)", "Mutual Information"},*)
(*      PlotStyle  -> {Thick, Purple},        commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "EntropyA"       <> ext}],*)
(*    ListLinePlot[get["EntropyA"],*)
(*      FrameLabel -> {"Time (t)", "Entropy A"},*)
(*      PlotStyle  -> {Thick, Orange},        commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "EntropyB"       <> ext}],*)
(*    ListLinePlot[get["EntropyB"],*)
(*      FrameLabel -> {"Time (t)", "Entropy B"},*)
(*      PlotStyle  -> {Thick, Darker[Orange]}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "Purity"         <> ext}],*)
(*    ListLinePlot[get["Purity"],*)
(*      FrameLabel -> {"Time (t)", "Purity"},*)
(*      PlotStyle  -> {Thick, Darker[Green]}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "AllObservables" <> ext}],*)
(*    ListLinePlot[*)
(*      {get["SpinSurvival"], get["Concurrence"], get["Purity"],*)
(*       get["EntropyA"],     get["EntropyB"],    get["MutualInfo"]},*)
(*      FrameLabel  -> {"Time (t)", "Observables"},*)
(*      PlotStyle   -> {*)
(*        Directive[Thick, Blue],*)
(*        Directive[Thick, Red],*)
(*        Directive[Thick, Darker[Green], Dashed],*)
(*        Directive[Thick, Orange],*)
(*        Directive[Thick, Darker[Orange], Dashed],*)
(*        Directive[Thick, Purple, DotDashed]},*)
(*      PlotLegends -> Placed[LineLegend[*)
(*        {"Spin Survival", "Concurrence", "Purity",*)
(*         "Entropy A", "Entropy B", "Mutual Info"},*)
(*        LegendFunction -> Framed], Right],*)
(*      commonOpts]];*)
(**)
(*(* Binary .mx for fast Mathematica reloading *)*)
(*Export[FileNameJoin[{dir, "data_D" <> StringPadLeft[ToString[k], 2, "0"] <> ".mx"}],*)
(*  results];*)
(**)
(*];*)


(* ::Input:: *)
(*(* ============================================================ *)*)
(*(* CHAPTER: Automated sweep                                     *)*)
(*(* \[CapitalDelta] \[Element] {0.0, 0.1, ..., 2.0}  \[Times]  L \[Element] {3, 4, 5, 6, 7, 8}       *)*)
(*(* Folder per L, one PNG per observable per (L,\[CapitalDelta]) run          *)*)
(*(* ============================================================ *)*)
(**)
(*(* ---------------------------------------------------------------- *)*)
(*(* Fixed parameters \[LongDash] identical across all runs                     *)*)
(*(* ---------------------------------------------------------------- *)*)
(*{\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = {1, 1, 0.35, 0.35};*)
(*{h1sweep, h2sweep} = {0.99, 1.01};*)
(*tMax  = 100.;*)
(*dt    = 0.1;*)
(*tlist = Range[0., tMax, dt];*)
(**)
(*HAlocal   = \[CapitalDelta]a * \[Sigma]z;*)
(*HBlocal   = \[CapitalDelta]b * \[Sigma]z;*)
(*couplingA = {{\[Lambda]a, \[Sigma]p, \[Sigma]m}, {\[Lambda]a, \[Sigma]m, \[Sigma]p}};*)
(*couplingB = {{\[Lambda]b, \[Sigma]p, \[Sigma]m}, {\[Lambda]b, \[Sigma]m, \[Sigma]p}};*)
(**)
(*(* Bell state \[LongDash] constant reference across all runs *)*)
(*bellState  = {1, 0, 0, 1}/Sqrt[2.];*)
(*rhoABspin  = Outer[Times, bellState, Conjugate[bellState]];*)
(*rhoABref   = rhoABspin;*)
(**)
(*(* Sweep ranges *)*)
(*LList      = Range[5,7];*)
(*kDeltaList = Range[0, 20];   (* integer keys: \[CapitalDelta] = k/10 exactly *)*)
(**)
(*(* Base output directory \[LongDash] same folder as the notebook *)*)
(*baseDir = NotebookDirectory[];*)


(* ::Input:: *)
(*(* ---------------------------------------------------------------- *)*)
(*(* Main sweep                                                        *)*)
(*(* ---------------------------------------------------------------- *)*)
(*Do[*)
(*  (* Create output folder for this L *)*)
(*  dirL = FileNameJoin[{baseDir, "L=" <> ToString[L]}];*)
(*  If[!DirectoryQ[dirL], CreateDirectory[dirL]];*)
(**)
(*  (* Chain initial state depends on L only \[LongDash] built once per L *)*)
(*  rhoChainSweep = Dyad[coherentstate[qubit[1., 0], L]];*)
(*(*rhoChainSweep = Dyad[RandomChainProductState[L]];*)*)
(*rho0sweep     = BuildInitialStateCorrelated[rhoABspin, rhoChainSweep, L];*)
(**)
(*  Do[*)
(*    delta = N[k/10];*)
(*    t0    = AbsoluteTime[];*)
(*    Print["L = ", L, "   \[CapitalDelta] = ", NumberForm[delta, {3,1}], "   ..."];*)
(**)
(*    (* Build and diagonalize *)*)
(*    (*Ha           = OpenXXZHamiltonian[L, delta, h1sweep, h2sweep];*)*)
(*Ha=IsingHamiltonian[1.05,delta,1,L,BoundaryConditions->"Open"];*)
(*HT           = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal,*)
(*                         couplingA, couplingB, L]];*)
(*    {Eval, Evec} = DiagonalizeH[HT];*)
(*    Clear[Ha, HT];*)
(**)
(*    (* Precompute *)*)
(*    rhoE   = ProjectToEnergyBasis[Evec, rho0sweep];*)
(*    Tmat   = BuildTransferTensors[Evec, L];*)
(*    Kmat   = BuildKMatrix[rhoE, Tmat];*)
(*    Clear[Tmat, Evec];*)
(*    dEflat = BuildEnergyDiffs[Chop[Eval]];*)
(*    Gflat  = BuildGflat[rhoE];*)
(*    Clear[rhoE, Eval];*)
(**)
(*    (* Distribute to parallel kernels *)*)
(*    DistributeDefinitions[*)
(*      Kmat, dEflat, Gflat, rhoABref, spinFlip,*)
(*      TraceOutA, TraceOutB, VNEntropy2x2, VNEntropy4x4,*)
(*      Concurrence, ComputeAllObservables,*)
(*      ComputeRhoAB, ComputeSurvivalGlobal*)
(*    ];*)
(**)
(*    (* Time evolution *)*)
(*    allResults = ParallelTable[*)
(*      Module[{rhoABt, survGlobal, obs},*)
(*        rhoABt     = Chop[ComputeRhoAB[Kmat, dEflat, t]];*)
(*        survGlobal = ComputeSurvivalGlobal[Gflat, dEflat, t];*)
(*        obs        = ComputeAllObservables[rhoABt, rhoABref];*)
(*        Join[<|"Time" -> t, "SurvivalGlobal" -> survGlobal|>, obs]*)
(*      ],*)
(*      {t, tlist},*)
(*      DistributedContexts -> None*)
(*    ];*)
(*    Clear[Kmat, dEflat, Gflat];*)
(**)
(*    (* Export all plots for this run *)*)
(*    MakePlots[allResults, L, k, dirL];*)
(*    Clear[allResults];*)
(**)
(*    Print["      done in ", Round[AbsoluteTime[] - t0, 0.1], " s"];*)
(**)
(*    , {k, kDeltaList}*)
(*  ];*)
(**)
(*  , {L, LList}*)
(*];*)
(**)
(*Print["Sweep complete."];*)


(* ::Title:: *)
(*Cycle \[Rho]_thermal*)


(* ::Input:: *)
(*(* ============================================================ *)*)
(*(* NEW FUNCTION: Thermal state of the chain                      *)*)
(*(* Ha: 2^L x 2^L chain Hamiltonian (numerical)                  *)*)
(*(* beta: inverse temperature (0 = infinite T, Infinity = T=0)   *)*)
(*(* ============================================================ *)*)
(*Clear[ThermalChainState];*)
(*ThermalChainState[Ha_, beta_] := Module[*)
(*  {vals, vecs, weights, Z},*)
(*  Which[*)
(*    (* Infinite temperature: maximally mixed state *)*)
(*    beta == 0.,*)
(*      N[IdentityMatrix[Length[Ha]]] / Length[Ha],*)
(**)
(*    (* Zero temperature: ground state projector *)*)
(*    beta === Infinity,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      Outer[Times, vecs[[1]], Conjugate[vecs[[1]]]],*)
(**)
(*    (* General case: Gibbs state *)*)
(*    True,*)
(*      {vals, vecs} = Transpose[Sort[Transpose[Eigensystem[N[Ha]]]]];*)
(*      (* Subtract Min[vals] for numerical stability \[LongDash] cancels in ratio *)*)
(*      weights = Exp[-beta * (vals - Min[vals])];*)
(*      Z = Total[weights];*)
(*      ConjugateTranspose[vecs] . DiagonalMatrix[N[weights / Z]] . vecs*)
(*  ]*)
(*];*)


(* ::Input:: *)
(*(* ============================================================ *)*)
(*(* HELPER: Beta label strings for filenames and plot labels      *)*)
(*(* ============================================================ *)*)
(*BetaStr[beta_] := Which[*)
(*  beta == 0.,           "b0p0",*)
(*  beta == 0.5,          "b0p5",*)
(*  beta == 1.,           "b1p0",*)
(*  beta == 2.,           "b2p0",*)
(*  beta === Infinity,    "bInf",*)
(*  True, "b" <> StringReplace[*)
(*          ToString[NumberForm[N[beta], {3,1}]], "." -> "p"]*)
(*];*)
(*BetaLabel[beta_] := Which[*)
(*  beta == 0.,         "\[Beta]=0  (T\[Rule]\[Infinity])",*)
(*  beta === Infinity,  "\[Beta]=\[Infinity]  (T=0)",*)
(*  True, "\[Beta]=" <> ToString[NumberForm[N[beta], {3,1}]]*)
(*];*)


(* ::Input:: *)
(*(* ============================================================ *)*)
(*(* UPDATED MakePlots: add beta_ argument                         *)*)
(*(* Only changes: label and ext now include beta                  *)*)
(*(* ============================================================ *)*)
(*MakePlots[results_, L_, k_, beta_, dir_] := Module[*)
(*  {delta, label, ext, get, commonOpts},*)
(**)
(*  delta = N[k/10];*)
(*  label = "XXZ,  L=" <> ToString[L] <>*)
(*          ",  \[CapitalDelta]=" <> ToString[NumberForm[delta, {3,1}]] <>*)
(*          ",  " <> BetaLabel[beta] <>*)
(*          ",  h1=" <> ToString[h1sweep] <>*)
(*          ",  h2=" <> ToString[h2sweep];*)
(*  ext = "_D" <> StringPadLeft[ToString[k], 2, "0"] <>*)
(*        "_"  <> BetaStr[beta] <> ".png";*)
(**)
(*  get[key_] := {#["Time"], #[key]} & /@ results;*)
(**)
(*  commonOpts = Sequence[*)
(*    Frame      -> True,*)
(*    LabelStyle -> Directive[Black, 16],*)
(*    PlotLabel  -> Style[label, Black, 13],*)
(*    ImageSize  -> 700,*)
(*    PlotRange  -> All*)
(*  ];*)
(**)
(*  (* All Export calls identical to before \[LongDash] only ext and label changed *)*)
(*  Export[FileNameJoin[{dir, "Concurrence"    <> ext}],*)
(*    ListLinePlot[get["Concurrence"],*)
(*      FrameLabel -> {"Time (t)", "Concurrence"},*)
(*      PlotStyle  -> {Thick, Red}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "SpinSurvival"   <> ext}],*)
(*    ListLinePlot[get["SpinSurvival"],*)
(*      FrameLabel -> {"Time (t)", "Spin Survival"},*)
(*      PlotStyle  -> {Thick, Blue}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "MutualInfo"     <> ext}],*)
(*    ListLinePlot[get["MutualInfo"],*)
(*      FrameLabel -> {"Time (t)", "Mutual Information"},*)
(*      PlotStyle  -> {Thick, Purple}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "EntropyA"       <> ext}],*)
(*    ListLinePlot[get["EntropyA"],*)
(*      FrameLabel -> {"Time (t)", "Entropy A"},*)
(*      PlotStyle  -> {Thick, Orange}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "EntropyB"       <> ext}],*)
(*    ListLinePlot[get["EntropyB"],*)
(*      FrameLabel -> {"Time (t)", "Entropy B"},*)
(*      PlotStyle  -> {Thick, Darker[Orange]}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "Purity"         <> ext}],*)
(*    ListLinePlot[get["Purity"],*)
(*      FrameLabel -> {"Time (t)", "Purity"},*)
(*      PlotStyle  -> {Thick, Darker[Green]}, commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir, "AllObservables" <> ext}],*)
(*    ListLinePlot[*)
(*      {get["SpinSurvival"], get["Concurrence"], get["Purity"],*)
(*       get["EntropyA"],     get["EntropyB"],    get["MutualInfo"]},*)
(*      FrameLabel  -> {"Time (t)", "Observables"},*)
(*      PlotStyle   -> {*)
(*        Directive[Thick, Blue], Directive[Thick, Red],*)
(*        Directive[Thick, Darker[Green], Dashed],*)
(*        Directive[Thick, Orange],*)
(*        Directive[Thick, Darker[Orange], Dashed],*)
(*        Directive[Thick, Purple, DotDashed]},*)
(*      PlotLegends -> Placed[LineLegend[*)
(*        {"Spin Survival", "Concurrence", "Purity",*)
(*         "Entropy A", "Entropy B", "Mutual Info"},*)
(*        LegendFunction -> Framed], Right],*)
(*      commonOpts]];*)
(**)
(*  Export[FileNameJoin[{dir,*)
(*    "data_D" <> StringPadLeft[ToString[k], 2, "0"] <>*)
(*    "_" <> BetaStr[beta] <> ".mx"}],*)
(*    results];*)
(*];*)


(* ::Input:: *)
(*(* ---------------------------------------------------------------- *)*)
(*(* Fixed parameters \[LongDash] identical across all runs                     *)*)
(*(* ---------------------------------------------------------------- *)*)
(*{\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = {1, 1, 0.35, 0.35};*)
(*{h1sweep, h2sweep} = {0.99, 1.01};*)
(*tMax  = 200.;*)
(*dt    = 0.1;*)
(*tlist = Range[0., tMax, dt];*)
(**)
(*HAlocal   = \[CapitalDelta]a * \[Sigma]z;*)
(*HBlocal   = \[CapitalDelta]b * \[Sigma]z;*)
(*couplingA = {{\[Lambda]a, \[Sigma]p, \[Sigma]m}, {\[Lambda]a, \[Sigma]m, \[Sigma]p}};*)
(*couplingB = {{\[Lambda]b, \[Sigma]p, \[Sigma]m}, {\[Lambda]b, \[Sigma]m, \[Sigma]p}};*)
(**)
(*(* Bell state \[LongDash] constant reference across all runs *)*)
(*bellState  = {1, 0, 0, 1}/Sqrt[2.];*)
(*rhoABspin  = Outer[Times, bellState, Conjugate[bellState]];*)
(*rhoABref   = rhoABspin;*)
(**)
(*delta = 1.;   (* integer keys: \[CapitalDelta] = k/10 exactly *)*)
(**)
(*(* Base output directory \[LongDash] same folder as the notebook *)*)
(*baseDir = NotebookDirectory[];*)


(* ::Input:: *)
(*(* ============================================================ *)*)
(*(* UPDATED SWEEP: new beta loop, restructured clearing           *)*)
(*(* Total runs: |LList| x |kDeltaList| x |betaList| = 5x21x6    *)*)
(*(*             (adjust LList/kDeltaList to your current range)  *)*)
(*(* ============================================================ *)*)
(*betaList = {0.,0.01,0.5, 1., 2.,100,Infinity};*)


(* ::Input:: *)
(*(* Sweep ranges *)*)
(*LList      = Range[3,7];*)


(* ::Input:: *)
(*Do[*)
(*  dirL = FileNameJoin[{baseDir, "L=" <> ToString[L]}];*)
(*  If[!DirectoryQ[dirL], CreateDirectory[dirL]];*)
(**)
(*  Do[*)
(*    delta = N[k/10];*)
(*    Print["L = ", L, "  \[CapitalDelta] = ", NumberForm[delta,{3,1}], "  ..."];*)
(*    t0 = AbsoluteTime[];*)
(**)
(*    (* \[HorizontalLine]\[HorizontalLine] Build and diagonalise ONCE per (L, \[CapitalDelta]) \[HorizontalLine]\[HorizontalLine] *)*)
(*    Ha           = OpenXXZHamiltonian[L, delta, h1sweep, h2sweep];*)
(*    HT           = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal,*)
(*                         couplingA, couplingB, L]];*)
(*    {Eval, Evec} = DiagonalizeH[HT];*)
(*    Clear[HT];*)
(**)
(*    (* Transfer tensors and energy diffs are \[Beta]-independent \[RightArrow] compute once *)*)
(*    Tmat   = BuildTransferTensors[Evec, L];*)
(*    dEflat = BuildEnergyDiffs[Chop[Eval]];*)
(**)
(*    (* \[HorizontalLine]\[HorizontalLine] \[Beta] loop: only rhoE, Kmat, Gflat change \[HorizontalLine]\[HorizontalLine] *)*)
(*    Do[*)
(*      beta = betaList[[ib]];*)
(*      Print["    \[Beta] = ", BetaLabel[beta], "  ..."];*)
(**)
(*      (* Chain initial state depends on Ha and beta *)*)
(*      rhoChainSweep = ThermalChainState[Ha, beta];*)
(*      rho0sweep     = BuildInitialStateCorrelated[rhoABspin, rhoChainSweep, L];*)
(**)
(*      rhoE  = ProjectToEnergyBasis[Evec, rho0sweep];*)
(*      Kmat  = BuildKMatrix[rhoE, Tmat];       (* reuses Tmat *)*)
(*      Gflat = BuildGflat[rhoE];*)
(*      Clear[rhoE];*)
(**)
(*      DistributeDefinitions[*)
(*        Kmat, dEflat, Gflat, rhoABref, spinFlip,*)
(*        TraceOutA, TraceOutB, VNEntropy2x2, VNEntropy4x4,*)
(*        Concurrence, ComputeAllObservables,*)
(*        ComputeRhoAB, ComputeSurvivalGlobal*)
(*      ];*)
(**)
(*      allResults = ParallelTable[*)
(*        Module[{rhoABt, survGlobal, obs},*)
(*          rhoABt     = Chop[ComputeRhoAB[Kmat, dEflat, t]];*)
(*          survGlobal = ComputeSurvivalGlobal[Gflat, dEflat, t];*)
(*          obs        = ComputeAllObservables[rhoABt, rhoABref];*)
(*          Join[<|"Time" -> t, "SurvivalGlobal" -> survGlobal|>, obs]*)
(*        ],*)
(*        {t, tlist},*)
(*        DistributedContexts -> None*)
(*      ];*)
(*      Clear[Kmat, Gflat];*)
(**)
(*      MakePlots[allResults, L, k, beta, dirL];    (* beta added *)*)
(*      Clear[allResults];*)
(**)
(*      , {ib, Length[betaList]}*)
(*    ];*)
(**)
(*    (* Ha, Tmat, Evec, Eval cleared AFTER the full \[Beta] loop *)*)
(*    Clear[Ha, Tmat, Evec, Eval, dEflat];*)
(*    Print["  (L=", L, ", \[CapitalDelta]=", NumberForm[delta,{3,1}],*)
(*          ") all \[Beta] done in ", Round[AbsoluteTime[]-t0, 0.1], " s"];*)
(**)
(*    , {k, kDeltaList}*)
(*  ];*)
(**)
(*  , {L, LList}*)
(*];*)
(**)
(*Print["Sweep complete."];*)


(* ::Input:: *)
(*Do[*)
(*  dirL = FileNameJoin[{baseDir, "L=" <> ToString[L]}];*)
(*  If[!DirectoryQ[dirL], CreateDirectory[dirL]];*)
(**)
(*  (* Build and diagonalise ONCE per L, at fixed delta *)*)
(*  Ha           = OpenXXZHamiltonian[L, delta, h1sweep, h2sweep];*)
(*  HT           = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal,*)
(*                       couplingA, couplingB, L]];*)
(*  {Eval, Evec} = DiagonalizeH[HT];*)
(*  Clear[HT];*)
(**)
(*  (* Transfer tensors and energy diffs are \[Beta]-independent \[RightArrow] compute once per L *)*)
(*  Tmat   = BuildTransferTensors[Evec, L];*)
(*  dEflat = BuildEnergyDiffs[Chop[Eval]];*)
(**)
(*  (* \[Beta] loop: only rhoE, Kmat, Gflat change *)*)
(*  Do[*)
(*    beta = betaList[[ib]];*)
(*    Print["L = ", L, "   \[Beta] = ", BetaLabel[beta], "   ..."];*)
(*    t0 = AbsoluteTime[];*)
(**)
(*    rhoChainSweep = ThermalChainState[Ha, beta];*)
(*    rho0sweep     = BuildInitialStateCorrelated[rhoABspin, rhoChainSweep, L];*)
(**)
(*    rhoE  = ProjectToEnergyBasis[Evec, rho0sweep];*)
(*    Kmat  = BuildKMatrix[rhoE, Tmat];*)
(*    Gflat = BuildGflat[rhoE];*)
(*    Clear[rhoE];*)
(**)
(*    DistributeDefinitions[*)
(*      Kmat, dEflat, Gflat, rhoABref, spinFlip,*)
(*      TraceOutA, TraceOutB, VNEntropy2x2, VNEntropy4x4,*)
(*      Concurrence, ComputeAllObservables,*)
(*      ComputeRhoAB, ComputeSurvivalGlobal*)
(*    ];*)
(**)
(*    allResults = ParallelTable[*)
(*      Module[{rhoABt, survGlobal, obs},*)
(*        rhoABt     = Chop[ComputeRhoAB[Kmat, dEflat, t]];*)
(*        survGlobal = ComputeSurvivalGlobal[Gflat, dEflat, t];*)
(*        obs        = ComputeAllObservables[rhoABt, rhoABref];*)
(*        Join[<|"Time" -> t, "SurvivalGlobal" -> survGlobal|>, obs]*)
(*      ],*)
(*      {t, tlist},*)
(*      DistributedContexts -> None*)
(*    ];*)
(*    Clear[Kmat, Gflat];*)
(**)
(*    MakePlots[allResults, L, k, beta, dirL];*)
(*    Clear[allResults];*)
(**)
(*    Print["      done in ", Round[AbsoluteTime[] - t0, 0.1], " s"];*)
(**)
(*    , {ib, Length[betaList]}*)
(*  ];*)
(**)
(*  (* Ha, Tmat, Evec, Eval cleared after the full \[Beta] loop for this L *)*)
(*  Clear[Ha, Tmat, Evec, Eval, dEflat];*)
(**)
(*  , {L, LList}*)
(*];*)
(**)
(*Print["Sweep complete."];*)



