(* ::Package:: *)

(* ::Title:: *)
(*Spin channels - state-vector engine*)


(* ::Chapter:: *)
(*Definitions*)


(* ::Section:: *)
(*0 - Session setup*)


(* ::Input:: *)
(*(* Compile target for this session. Falls back to "WVM" if no C compiler. *)*)
(*$CompileTarget = "C";*)


(* ::Section:: *)
(*1 - Compiled partial traces (4x4 rhoAB, layout (q1,q2))*)


(* ::Input:: *)
(*Clear[TraceOutA, TraceOutB];*)
(*TraceOutB = Compile[                  (* keep spin A, trace out B *)*)
(*  {{\[Rho], _Complex, 2}},*)
(*  {{\[Rho][[1,1]] + \[Rho][[2,2]],  \[Rho][[1,3]] + \[Rho][[2,4]]},*)
(*   {\[Rho][[3,1]] + \[Rho][[4,2]],  \[Rho][[3,3]] + \[Rho][[4,4]]}},*)
(*  CompilationTarget -> $CompileTarget, RuntimeOptions -> "Speed"*)
(*];*)
(*TraceOutA = Compile[                  (* keep spin B, trace out A *)*)
(*  {{\[Rho], _Complex, 2}},*)
(*  {{\[Rho][[1,1]] + \[Rho][[3,3]],  \[Rho][[1,2]] + \[Rho][[3,4]]},*)
(*   {\[Rho][[2,1]] + \[Rho][[4,3]],  \[Rho][[2,2]] + \[Rho][[4,4]]}},*)
(*  CompilationTarget -> $CompileTarget, RuntimeOptions -> "Speed"*)
(*];*)


(* ::Section:: *)
(*2 - Von Neumann entropy*)


(* ::Input:: *)
(*Clear[VNEntropy2x2, VNEntropy4x4];*)
(*VNEntropy2x2 = Compile[*)
(*  {{\[Rho], _Complex, 2}},*)
(*  Module[{r11, r22, r12r, r12i, absq, disc, \[Lambda]1, \[Lambda]2},*)
(*    r11  = Re[\[Rho][[1,1]]]; r22 = Re[\[Rho][[2,2]]];*)
(*    r12r = Re[\[Rho][[1,2]]]; r12i = Im[\[Rho][[1,2]]];*)
(*    absq = r12r^2 + r12i^2;*)
(*    disc = Sqrt[(r11 - r22)^2 + 4.*absq];*)
(*    \[Lambda]1 = (r11 + r22 + disc)/2.; \[Lambda]2 = (r11 + r22 - disc)/2.;*)
(*    If[\[Lambda]1 > 1.*^-14, -\[Lambda]1*Log[\[Lambda]1], 0.] +*)
(*    If[\[Lambda]2 > 1.*^-14, -\[Lambda]2*Log[\[Lambda]2], 0.]*)
(*  ],*)
(*  CompilationTarget -> $CompileTarget, RuntimeOptions -> "Speed"*)
(*];*)
(*VNEntropy4x4[\[Rho]_] := Module[*)
(*  {\[Lambda] = Select[Re[Eigenvalues[N[\[Rho]]]], # > 1.*^-14 &]},*)
(*  -\[Lambda] . Log[\[Lambda]]*)
(*];*)


(* ::Section:: *)
(*3 - Concurrence (Wootters 1998)*)


(* ::Input:: *)
(*spinFlip = N[KroneckerProduct[PauliMatrix[2], PauliMatrix[2]]];*)
(*Clear[Concurrence];*)
(*Concurrence[\[Rho]_] := Module[*)
(*  {\[Rho]Tilde, \[Lambda]s},*)
(*  \[Rho]Tilde = spinFlip . Conjugate[\[Rho]] . spinFlip;*)
(*  \[Lambda]s = Reverse[Sort[Re[Sqrt[Chop[Eigenvalues[\[Rho] . \[Rho]Tilde]]]]]];*)
(*  Max[0., \[Lambda]s[[1]] - \[Lambda]s[[2]] - \[Lambda]s[[3]] - \[Lambda]s[[4]]]*)
(*];*)


(* ::Section:: *)
(*4 - Single-pass observable aggregator*)


(* ::Input:: *)
(*Clear[ComputeAllObservables];*)
(*ComputeAllObservables[\[Rho]AB_, \[Rho]ref_] := Module[*)
(*  {\[Rho]A, \[Rho]B, SA, SB, SAB},*)
(*  \[Rho]A = TraceOutB[\[Rho]AB]; \[Rho]B = TraceOutA[\[Rho]AB];*)
(*  SA = VNEntropy2x2[\[Rho]A]; SB = VNEntropy2x2[\[Rho]B];*)
(*  SAB = VNEntropy4x4[\[Rho]AB];*)
(*  <|*)
(*    "Concurrence"  -> Concurrence[\[Rho]AB],*)
(*    "Purity"       -> Re[Tr[\[Rho]AB . \[Rho]AB]],*)
(*    "EntropyA"     -> SA,*)
(*    "EntropyB"     -> SB,*)
(*    "MutualInfo"   -> SA + SB - SAB,*)
(*    "SpinSurvival" -> Re[Tr[\[Rho]ref . \[Rho]AB]]   (* overlap with reference; a fidelity only if \[Rho]ref is pure *)*)
(*  |>*)
(*];*)


(* ::Section:: *)
(*5 - Pauli operators*)


(* ::Input:: *)
(*\[Sigma]x = N[PauliMatrix[1]]; \[Sigma]y = N[PauliMatrix[2]]; \[Sigma]z = N[PauliMatrix[3]];*)
(*\[Sigma]p = \[Sigma]x + I*\[Sigma]y;   (* raising:  {{0,2},{0,0}} *)*)
(*\[Sigma]m = \[Sigma]x - I*\[Sigma]y;   (* lowering: {{0,0},{2,0}} *)*)
(*id2 = N[IdentityMatrix[2]];*)


(* ::Section:: *)
(*6 - Hamiltonian embeddings and boundary couplings*)


(* ::Input:: *)
(*Clear[SparseId, EmbedSpinA, EmbedSpinB, EmbedChain, EmbedChainSite];*)
(*SparseId[n_] := SparseArray[Band[{1, 1}] -> 1., {n, n}];*)
(*EmbedSpinA[op_, L_]      := KroneckerProduct[op, SparseId[2^L], SparseId[2]];*)
(*EmbedSpinB[op_, L_]      := KroneckerProduct[SparseId[2], SparseId[2^L], op];*)
(*EmbedChain[Ha_, L_]      := KroneckerProduct[SparseId[2], Ha, SparseId[2]];*)
(*EmbedChainSite[op_, k_, L_] := KroneckerProduct[SparseId[2^(k-1)], op, SparseId[2^(L-k)]];*)
(**)
(*Clear[BuildCouplingAChain, BuildCouplingBChain, BuildFullHamiltonian];*)
(*(* A couples to the FIRST chain site; B to the LAST. *)*)
(*BuildCouplingAChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[term[[2]], KroneckerProduct[term[[3]], SparseId[2^(L-1)]], SparseId[2]],*)
(*  {term, couplingTerms}];*)
(*BuildCouplingBChain[couplingTerms_, L_] := Sum[*)
(*  term[[1]] * KroneckerProduct[SparseId[2], KroneckerProduct[SparseId[2^(L-1)], term[[2]]], term[[3]]],*)
(*  {term, couplingTerms}];*)
(*BuildFullHamiltonian[HAlocal_, Ha_, HBlocal_, couplingA_, couplingB_, L_] :=*)
(*  EmbedSpinA[HAlocal, L] + EmbedChain[Ha, L] + EmbedSpinB[HBlocal, L] +*)
(*  BuildCouplingAChain[couplingA, L] + BuildCouplingBChain[couplingB, L];*)


(* ::Section:: *)
(*7 - Chain Hamiltonian (self-contained; matches XXZwLocalDefectHamiltonian)*)


(* ::Input:: *)
(*(* Open XXZ chain with uniform field w and local defect field ed on site d:      *)*)
(*(*   H = Sum_k (1/4)[ Jxy(XX+YY) + Jz ZZ ]  +  (1/2)( w Sum_k Zk + ed Z_d ).       *)*)
(*(* Anisotropy is the Jz slot. Prefer the QMB library version if it is loaded.       *)*)
(*Clear[XXZChainSparse];*)
(*XXZChainSparse[Jxy_, Jz_, w_, ed_, L_, d_] := Module[*)
(*  {dim = 2^L, H, embNN, emb},*)
(*  emb[op_, k_]        := KroneckerProduct[SparseId[2^(k-1)], op, SparseId[2^(L-k)]];*)
(*  embNN[oa_, ob_, k_] := KroneckerProduct[SparseId[2^(k-1)], oa, ob, SparseId[2^(L-k-1)]];*)
(*  H = SparseArray[{}, {dim, dim}];*)
(*  Do[H += (1/4)*(Jxy*(embNN[\[Sigma]x, \[Sigma]x, k] + embNN[\[Sigma]y, \[Sigma]y, k]) + Jz*embNN[\[Sigma]z, \[Sigma]z, k]),*)
(*     {k, 1, L-1}];*)
(*  If[w  != 0., Do[H += (1/2)*w*emb[\[Sigma]z, k], {k, 1, L}]];*)
(*  If[ed != 0., H += (1/2)*ed*emb[\[Sigma]z, d]];*)
(*  H*)
(*];*)


(* ::Section:: *)
(*8 - Diagonalization (real-symmetric aware)*)


(* ::Input:: *)
(*(* If H is real symmetric (guard passes) the real eigensolver is used: real       *)*)
(*(* eigenvectors, ~half the memory and time of the complex path. Eigenvectors are   *)*)
(*(* returned as ROWS, sorted by ascending energy.                                   *)*)
(*Clear[DiagonalizeH];*)
(*DiagonalizeH::cmplx = "Hamiltonian has imaginary part up to `1`; complex eigensolver used.";*)
(*DiagonalizeH[HT_] := Module[*)
(*  {HN = N[HT], im, vals, vecs, ord},*)
(*  im = Max[Abs[Im[If[Head[HN] === SparseArray, HN["NonzeroValues"], Flatten[HN]]]]];*)
(*  If[im > 1.*^-12,*)
(*    Message[DiagonalizeH::cmplx, im]; HN = Normal[HN],*)
(*    HN = Re[Normal[HN]]*)
(*  ];*)
(*  {vals, vecs} = Eigensystem[HN];*)
(*  ord = Ordering[vals];*)
(*  {vals[[ord]], vecs[[ord]]}*)
(*];*)


(* ::Section:: *)
(*9 - Wavefunction utilities*)


(* ::Input:: *)
(*Clear[BuildInitialStateVector, GetRhoAB];*)
(*(* psiAB: length-4 (q1,q2);  psiChain: length-2^L.  Output layout: (q1, c, q2).    *)*)
(*BuildInitialStateVector[psiAB_List, psiChain_List, L_] := Module[{tensor},*)
(*  tensor = TensorProduct[ArrayReshape[psiAB, {2, 2}], psiChain];  (* (q1,q2,c) *)*)
(*  Flatten[Transpose[tensor, {1, 3, 2}]]                           (* (q1,c,q2) *)*)
(*];*)
(*(* Exact pure-state partial trace of the boundary spins from a (q1,c,q2) vector.    *)*)
(*GetRhoAB[psi_, L_] := Module[{M},*)
(*  M = ArrayReshape[Transpose[ArrayReshape[psi, {2, 2^L, 2}], {1, 3, 2}], {4, 2^L}];*)
(*  M . ConjugateTranspose[M]*)
(*];*)


(* ::Section:: *)
(*10 - Thermal / ensemble state (defined here for testing)*)


(* ::Input:: *)
(*(* Chain state enters only as a list of {weight, eigenvector}. This keeps the      *)*)
(*(* engine agnostic to how the mixture was produced (thermal, ground, product...).  *)*)
(*Clear[ThermalWeights, ThermalChainStates, ThermalChainDensity];*)
(**)
(*(* beta == 0        -> maximally mixed (uniform weights)                            *)*)
(*(* beta == Infinity -> equal-weight ground multiplet (degeneracy-safe)             *)*)
(*(* else             -> Boltzmann weights, shifted by ground energy for stability    *)*)
(*ThermalWeights[valsChain_, beta_] := Module[{v0, w, tol},*)
(*  Which[*)
(*    beta == 0.,*)
(*      ConstantArray[1./Length[valsChain], Length[valsChain]],*)
(*    beta === Infinity,*)
(*      v0 = Min[valsChain]; tol = 1.*^-10 Max[1., Abs[v0]];*)
(*      w = Boole[(valsChain - v0) <= tol]; w/Total[w],*)
(*    True,*)
(*      v0 = Min[valsChain]; w = Exp[-beta (valsChain - v0)]; w/Total[w]*)
(*  ]*)
(*];*)
(**)
(*(* vecsChain: rows = eigenvectors (as returned by DiagonalizeH). thr = 0. is exact; *)*)
(*(* thr > 0 drops low-weight states (an approximation; retained weights not renorm). *)*)
(*ThermalChainStates[valsChain_, vecsChain_, beta_, thr_:0.] := Module[{w},*)
(*  w = ThermalWeights[valsChain, beta];*)
(*  Select[MapThread[{#1, #2} &, {w, vecsChain}], First[#] > thr &]*)
(*];*)
(**)
(*(* Full chain density matrix, for validation against MatrixExp[-beta Ha]/Tr.       *)*)
(*ThermalChainDensity[valsChain_, vecsChain_, beta_] := Module[{w = ThermalWeights[valsChain, beta]},*)
(*  Transpose[vecsChain] . (w vecsChain)*)
(*];*)


(* ::Input:: *)
(*(* Unravel rhoAB0 (x) rho_chain into sqrt(p)-weighted pure columns in the ENERGY   *)*)
(*(* basis. rhoAB0 may be mixed; chainStates = list of {weight, chainVector}.         *)*)
(*(* Returns PsiE0Mat : (2^(L+2)) x Nstates, ready for the evolution engine.          *)*)
(*Clear[BuildEnsembleColumns];*)
(*BuildEnsembleColumns[rhoAB0_, chainStates_, Evec_, L_] := Module[*)
(*  {vAB, UAB, cols},*)
(*  {vAB, UAB} = Eigensystem[N[rhoAB0]];        (* rows = eigenvectors *)*)
(*  cols = Reap[*)
(*    Do[*)
(*      Do[*)
(*        If[Re[vAB[[m]]] > 1.*^-12,*)
(*          Sow[ Sqrt[Re[vAB[[m]]] cs[[1]]] **)
(*               (Evec . BuildInitialStateVector[UAB[[m]], cs[[2]], L]) ]*)
(*        ],*)
(*        {m, Length[vAB]}*)
(*      ],*)
(*      {cs, chainStates}*)
(*    ]*)
(*  ][[2]];*)
(*  cols = If[cols === {}, {}, cols[[1]]];*)
(*  Transpose[cols]*)
(*];*)


(* ::Section:: *)
(*11 - Evolution engine (single kernel, batched BLAS)*)


(* ::Input:: *)
(*(* One engine for pure and mixed states. NO subkernels / DistributeDefinitions:    *)*)
(*(* the per-step cost is a dense D x (Ns*chunk) product handled by threaded BLAS on   *)*)
(*(* the master kernel. Distributing Evec (~2 GB at L=12) across kernels was the RAM   *)*)
(*(* multiplier in the old pipeline and is avoided here.                              *)*)
(*(*                                                                                  *)*)
(*(* Global survival Tr[rho(0) rho(t)]:                                               *)*)
(*(*   Ns == 1 : rank-1 form |probE . phase|^2  (no D x D object).                     *)*)
(*(*   Ns  > 1 : quadratic form Re[phase^* . (|rhoE0|^2 . phase)], |rhoE0|^2 built once.*)*)
(*Clear[EvolveEnsemble];*)
(*Options[EvolveEnsemble] = {"MaxColumns" -> 2048};*)
(*EvolveEnsemble[Eval_, Udag_, PsiE0Mat_, rhoABref_, L_, tlist_, OptionsPattern[]] := Module[*)
(*  {Ns, Dtot, dC, maxCols, chunk, tchunks, rank1, probE, absR2},*)
(*  Ns = Dimensions[PsiE0Mat][[2]];*)
(*  Dtot = Length[Eval]; dC = 2^L;*)
(*  maxCols = OptionValue["MaxColumns"];*)
(*  rank1 = (Ns == 1);*)
(*  If[rank1,*)
(*    probE = Abs[Flatten[PsiE0Mat]]^2,*)
(*    absR2 = Abs[PsiE0Mat . ConjugateTranspose[PsiE0Mat]]^2*)
(*  ];*)
(*  chunk = Max[1, Quotient[maxCols, Ns]];*)
(*  tchunks = Partition[tlist, UpTo[chunk]];*)
(*  Reap[*)
(*    Do[*)
(*      Module[{tc, c, phase, B, PsiBig},*)
(*        tc = tchunks[[ci]]; c = Length[tc];*)
(*        phase = Exp[(-I) Outer[Times, Eval, tc]];                       (* Dtot x c *)*)
(*        B = ArrayReshape[*)
(*              Transpose[Table[phase[[All, \[Tau]]] PsiE0Mat, {\[Tau], c}], {2, 1, 3}],*)
(*              {Dtot, c Ns}];                                            (* time-major *)*)
(*        PsiBig = Udag . B;                                             (* position basis *)*)
(*        Do[*)
(*          Module[{cols, M, rhoAB, ph, survG, obs},*)
(*            cols = PsiBig[[All, (\[Tau]-1) Ns + 1 ;; \[Tau] Ns]];*)
(*            M = ArrayReshape[*)
(*                  Transpose[ArrayReshape[cols, {2, dC, 2, Ns}], {1, 3, 2, 4}],*)
(*                  {4, dC Ns}];*)
(*            rhoAB = M . ConjugateTranspose[M];*)
(*            ph = phase[[All, \[Tau]]];*)
(*            survG = If[rank1, Abs[probE . ph]^2, Re[Conjugate[ph] . (absR2 . ph)]];*)
(*            obs = ComputeAllObservables[rhoAB, rhoABref];*)
(*            Sow[Join[<|"Time" -> tc[[\[Tau]]], "SurvivalGlobal" -> survG|>, obs]]*)
(*          ],*)
(*          {\[Tau], c}*)
(*        ]*)
(*      ],*)
(*      {ci, Length[tchunks]}*)
(*    ]*)
(*  ][[2, 1]]*)
(*];*)


(* ::Section:: *)
(*Notes (extension points)*)


(* ::Input:: *)
(*(* - Real arithmetic: DiagonalizeH enforces Re on Evec when H is real symmetric.    *)*)
(*(*   Complex-Hermitian H needs the projection convention revisited (Conjugate).     *)*)
(*(* - Exactness: ThermalChainStates thr = 0. keeps every chain state. thr > 0 is an  *)*)
(*(*   approximation; renormalize retained weights if you need Tr = 1 exactly.        *)*)
(*(* - Memory (mixed, Ns > 1): |rhoE0|^2 is D x D (~2 GB at L=12). For small Ns and    *)*)
(*(*   large D use instead the O(Ns^2) overlap form g = PsiE0Mat^dag.(phase PsiE0Mat), *)*)
(*(*   survival = Total[Abs[g]^2].                                                     *)*)
(*(* - Diagonalization is the one O(D^3)/O(D^2)-memory step. A U(1) Sz block-          *)*)
(*(*   diagonalization can replace DiagonalizeH without changing any downstream call. *)*)
(*(* - Tune "MaxColumns" to trade transient memory (D x MaxColumns) against BLAS batch *)*)
(*(*   efficiency.                                                                     *)*)


(* ::Chapter:: *)
(*Parameters*)


(* ::Input:: *)
(*(* ===============  MODEL + STATE  (single editable block)  =============== *)*)
(*(* --- System size and fields --- *)*)
(*L = 8;*)
(*{\[CapitalDelta]a, \[CapitalDelta]b, \[Lambda]a, \[Lambda]b} = {1., 1., 0.1, 0.1};*)
(*HAlocal = \[CapitalDelta]a \[Sigma]z;*)
(*HBlocal = \[CapitalDelta]b \[Sigma]z;*)
(*(* Flip-flop boundary coupling. NOTE: with \[Sigma]p=\[Sigma]x+I\[Sigma]y the effective XX+YY strength is 2\[Lambda]. *)*)
(*couplingA = {{\[Lambda]a, \[Sigma]p, \[Sigma]m}, {\[Lambda]a, \[Sigma]m, \[Sigma]p}};*)
(*couplingB = {{\[Lambda]b, \[Sigma]p, \[Sigma]m}, {\[Lambda]b, \[Sigma]m, \[Sigma]p}};*)
(**)
(*(* --- Chain (anisotropy in the Jz slot) --- *)*)
(*{Jxy, Jz, w, ed, d} = {1., 0.5, 0., 0., L};*)
(**)
(*(* --- Initial boundary state rhoAB0 (may be mixed) and its survival reference --- *)*)
(*bellState = {0., 1., 0, 0.};               (* Psi+  (Sz-definite) *)*)
(*rhoAB0    = Outer[Times, bellState, Conjugate[bellState]];*)
(*rhoABref  = rhoAB0;*)
(**)
(*(* --- Chain initial state --- *)*)
(*beta       = 100.;        (* 0. = maximally mixed, Infinity = ground multiplet *)*)
(*thermalThr = 0.;        (* 0. = exact; > 0 truncates (approximation) *)*)
(**)
(*(* --- Time grid and batching --- *)*)
(*tMax = 300.; *)
(*dt = 0.1;*)
(*tlist = Range[0., tMax, dt];*)
(*maxCols = 2048;*)


(* ::Chapter:: *)
(*Method*)


(* ::Input:: *)
(*(* --- One-time construction and diagonalization (depends on L and model only) --- *)*)
(*Ha            = XXZChainSparse[Jxy, Jz, w, ed, L, d];   (* or QMB`XXZwLocalDefectHamiltonian *)*)
(*HT            = Chop[BuildFullHamiltonian[HAlocal, Ha, HBlocal, couplingA, couplingB, L]];*)
(*{Eval, Evec}  = DiagonalizeH[HT];*)
(*Udag          = ConjugateTranspose[Evec];*)
(*{ChainVals, ChainVecs} = DiagonalizeH[Ha];*)


(* ::Input:: *)
(*(* --- Per-beta ensemble (rerun only this cell + the next when beta or rhoAB0 change) --- *)*)
(*chainStates = ThermalChainStates[ChainVals, ChainVecs, beta, thermalThr];*)
(*PsiE0Mat    = BuildEnsembleColumns[rhoAB0, chainStates, Evec, L];*)
(*Print["Nstates in ensemble: ", Dimensions[PsiE0Mat][[2]]];*)


(* ::Input:: *)
(*(* --- Time evolution --- *)*)
(*AbsoluteTiming[*)
(*  allResults = EvolveEnsemble[Eval, Udag, PsiE0Mat, rhoABref, L, tlist, "MaxColumns" -> maxCols];*)
(*]*)


(* ::Chapter:: *)
(*Results*)


(* ::Input:: *)
(*Clear[ExtractTimeSeries];*)
(*ExtractTimeSeries[key_] := {#["Time"], #[key]} & /@ allResults;*)
(*allResults[[1]]*)


(* ::Input:: *)
(*ListLinePlot[*)
(*  {ExtractTimeSeries["SpinSurvival"],*)
(*   ExtractTimeSeries["Concurrence"],*)
(*   ExtractTimeSeries["Purity"],*)
(*   ExtractTimeSeries["EntropyA"],*)
(*   ExtractTimeSeries["EntropyB"],*)
(*   ExtractTimeSeries["MutualInfo"]},*)
(*  Frame -> True,*)
(*  FrameLabel -> {"Time (t)", "Observables"},*)
(*  LabelStyle -> Directive[Black, 16],*)
(*  PlotStyle -> {*)
(*    Directive[Thick, Blue], Directive[Thick, Red],*)
(*    Directive[Thick, Darker[Green], Dashed], Directive[Thick, Orange],*)
(*    Directive[Thick, Purple], Directive[Thick, Darker[Red], DotDashed]*)
(*  },*)
(*  PlotLegends -> Placed[*)
(*    LineLegend[{"Spin Survival", "Concurrence", "Purity", "Entropy A", "Entropy B", "Mutual Info"},*)
(*      LegendFunction -> Framed], Right],*)
(*  ImageSize -> 1000, AspectRatio -> 0.5*)
(*]*)
